"""Build the readable PPC5r5 schema and inventory proposal artifacts.

This is proposal-generation tooling, not a PPC runtime implementation.  It
performs no model, tokenizer, trainer, environment, behavioral, or GPU work.
The generated bytes are reviewed and hash-bound like every other normative
source.  Keeping the repetitive JSON here makes the semantic choices visible
without hand-maintaining thousands of duplicated schema lines.
"""

from __future__ import annotations

import json
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "contracts.schema.json"
INVENTORY = ROOT / "object_inventory.json"
CONTROLLER_REGISTRY = ROOT / "controller_registry.json"
CLAIMS = json.loads((ROOT / "claim_dependency_map.json").read_text())

H = {"$ref": "#/$defs/hash"}
ID = {"$ref": "#/$defs/id"}
NID = {"$ref": "#/$defs/nullable_id"}
SYM = {"$ref": "#/$defs/symbol"}
BYTES = {"$ref": "#/$defs/bytes"}
RAT = {"$ref": "#/$defs/rational"}
PROB = {"$ref": "#/$defs/probability_rational"}
UNIT = {"$ref": "#/$defs/unit_rational"}
NUL_H = {"oneOf": [H, {"type": "null"}]}
NUL_ID = {"oneOf": [ID, {"type": "null"}]}
NUL_SYM = {"oneOf": [SYM, {"type": "null"}]}
NUL_RAT = {"oneOf": [RAT, {"type": "null"}]}


def arr(items, *, minimum=0, maximum=None, unique=False):
    result = {"type": "array", "items": items, "minItems": minimum}
    if maximum is not None:
        result["maxItems"] = maximum
    if unique:
        result["uniqueItems"] = True
    return result


def enum(*values):
    return {"enum": list(values)}


def integer(minimum=0, maximum=None):
    result = {"type": "integer", "minimum": minimum}
    if maximum is not None:
        result["maximum"] = maximum
    return result


def closed(required, properties, *, one_of=None):
    result = {
        "type": "object",
        "additionalProperties": False,
        "required": list(required),
        "properties": properties,
    }
    if one_of:
        result["oneOf"] = one_of
    return result


def top(contract, hash_field, fields, *, one_of=None):
    properties = {
        "contract": {"const": contract},
        "schema_version": {"const": 5},
        **fields,
        hash_field: H,
    }
    return closed(properties, properties, one_of=one_of)


def aref(role=None, artifact_types=None, ordinal=None):
    role_schema = {"const": role} if role else SYM
    type_schema = (
        enum(*artifact_types)
        if artifact_types
        else SYM
    )
    ordinal_schema = {"const": ordinal} if ordinal is not None else integer()
    return closed(
        ["role", "ordinal", "artifact_type", "sha256"],
        {
            "role": role_schema,
            "ordinal": ordinal_schema,
            "artifact_type": type_schema,
            "sha256": H,
        },
    )


def exact_refs(*roles):
    prefix = [aref(role, types, index) for index, (role, types) in enumerate(roles)]
    return {
        "type": "array",
        "prefixItems": prefix,
        "items": False,
        "minItems": len(prefix),
        "maxItems": len(prefix),
    }


def byte_ref(role=None, ordinal=None):
    return closed(
        ["role", "ordinal", "media_type", "relative_path", "byte_length", "raw_sha256"],
        {
            "role": {"const": role} if role else SYM,
            "ordinal": {"const": ordinal} if ordinal is not None else integer(),
            "media_type": SYM,
            "relative_path": {"type": "string", "pattern": "^(?!/)(?!.*(?:^|/)\\.\\.(?:/|$)).+$"},
            "byte_length": integer(),
            "raw_sha256": H,
        },
    )


def nullable(schema):
    return {"oneOf": [schema, {"type": "null"}]}


defs = {
    "hash": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
    "id": {"type": "string", "pattern": "^[a-z][a-z0-9]*-[0-9]{8}$"},
    "nullable_id": NUL_ID,
    "symbol": {"type": "string", "pattern": "^[A-Z][A-Z0-9_]{0,95}$"},
    "bytes": {"type": "string", "minLength": 1},
    "rational": closed(
        ["numerator", "denominator"],
        {"numerator": {"type": "integer"}, "denominator": integer(1)},
    ),
    "probability_rational": closed(
        ["numerator", "denominator"],
        {"numerator": integer(), "denominator": integer(1)},
    ),
    "unit_rational": closed(
        ["numerator", "denominator"],
        {"numerator": integer(), "denominator": integer(1)},
    ),
    "rational_bracket": closed(
        ["decimal_scale", "lower", "upper", "defining_tail", "tail_target"],
        {
            "decimal_scale": integer(),
            "lower": PROB,
            "upper": PROB,
            "defining_tail": enum("UPPER_BINOMIAL", "LOWER_BINOMIAL"),
            "tail_target": PROB,
        },
    ),
    "budget": closed(
        ["calls", "reads", "actions", "input_tokens", "output_tokens"],
        {
            "calls": integer(), "reads": integer(), "actions": integer(),
            "input_tokens": integer(), "output_tokens": integer(),
        },
    ),
    "artifact_ref": aref(),
    "byte_ref": byte_ref(),
    "human_evidence": closed(
        ["relative_path", "file_sha256", "excerpt_utf8", "excerpt_start_byte", "excerpt_end_byte_exclusive"],
        {
            "relative_path": {"type": "string", "pattern": "^(?!/).+$"},
            "file_sha256": H,
            "excerpt_utf8": BYTES,
            "excerpt_start_byte": integer(),
            "excerpt_end_byte_exclusive": integer(1),
        },
    ),
}


# Closed nested machine vocabulary.
defs["prediction"] = closed(
    ["action_id", "predicted_value"],
    {"action_id": ID, "predicted_value": UNIT},
)
defs["outcome"] = closed(
    ["action_id", "normalized_value", "environment_receipt_hash"],
    {"action_id": ID, "normalized_value": UNIT, "environment_receipt_hash": H},
)
defs["read_found"] = closed(
    ["contract", "status", "subject_id", "relation_id", "object_id", "record_id"],
    {
        "contract": {"const": "ppc5.read.v5"}, "status": {"const": "FOUND"},
        "subject_id": ID, "relation_id": ID, "object_id": ID, "record_id": ID,
    },
)
defs["read_null"] = closed(
    ["contract", "status", "subject_id", "relation_id", "object_id", "record_id"],
    {
        "contract": {"const": "ppc5.read.v5"},
        "status": enum("NOT_FOUND", "PROVIDER_MISSING_NO_RETRY"),
        "subject_id": {"type": "null"}, "relation_id": {"type": "null"},
        "object_id": {"type": "null"}, "record_id": {"type": "null"},
    },
)
defs["read_response"] = {"oneOf": [{"$ref": "#/$defs/read_found"}, {"$ref": "#/$defs/read_null"}]}
defs["op_read"] = closed(
    ["contract", "op", "subject_id", "relation_id"],
    {"contract": {"const": "ppc5.op.v5"}, "op": {"const": "READ"}, "subject_id": ID, "relation_id": ID},
)
defs["op_predict"] = closed(
    ["contract", "op", "prediction"],
    {"contract": {"const": "ppc5.op.v5"}, "op": {"const": "PREDICT"}, "prediction": {"$ref": "#/$defs/prediction"}},
)
defs["op_act"] = closed(
    ["contract", "op", "action_id"],
    {"contract": {"const": "ppc5.op.v5"}, "op": {"const": "ACT"}, "action_id": ID},
)
defs["op_stop"] = closed(
    ["contract", "op", "reason"],
    {"contract": {"const": "ppc5.op.v5"}, "op": {"const": "STOP"}, "reason": enum("MODEL_STOP", "NO_VALID_ACTION")},
)
defs["operation"] = {"oneOf": [{"$ref": f"#/$defs/{name}"} for name in ("op_read", "op_predict", "op_act", "op_stop")]}
defs["candidate"] = closed(
    ["candidate_id", "record_id", "subject_id", "relation_id", "object_id", "public_record"],
    {"candidate_id": ID, "record_id": ID, "subject_id": ID, "relation_id": ID, "object_id": ID, "public_record": byte_ref("PUBLIC_RECORD", 0)},
)
defs["terminal_payload"] = closed(
    ["origin", "reason", "attempted_call_id", "attempted_error_code", "attempted_debits", "queue_discard_refs", "endpoint_outcome_hash"],
    {
        "origin": enum("MODEL", "HARNESS", "CONTROLLER"),
        "reason": enum("SCHEDULE_COMPLETE", "PROVIDER_SEQUENCE_COMPLETE", "SCHEDULE_INCOMPLETE", "MODEL_STOP", "BUDGET_EXHAUSTED", "ERROR_LIMIT", "RUN_INVALID"),
        "attempted_call_id": NUL_ID,
        "attempted_error_code": NUL_SYM,
        "attempted_debits": {"$ref": "#/$defs/budget"},
        "queue_discard_refs": arr(aref("QUEUE_DISCARD", ["QUEUE_EFFECT_RECEIPT"])),
        "endpoint_outcome_hash": NUL_H,
    },
)


defs["byte_artifact_manifest"] = top(
    "ppc5.byte_artifact_manifest.v5", "manifest_hash",
    {
        "artifact_id": ID,
        "artifact_kind": enum("MODEL", "TOKENIZER", "ADAPTER", "PROMPT", "SOURCE_TREE", "FIXTURE", "EXECUTABLE", "LOG", "CORPUS"),
        "root_name": SYM,
        "files": arr(byte_ref(), minimum=1),
        "tree_hash": H,
    },
)
defs["parameter_axis"] = closed(
    ["axis_ordinal", "name", "ordered_value_hashes", "sampling_rule"],
    {"axis_ordinal": integer(), "name": SYM, "ordered_value_hashes": arr(H, minimum=1, unique=True), "sampling_rule": {"const": "UNIFORM"}},
)
defs["generator_parameter_space"] = top(
    "ppc5.generator_parameter_space.v5", "manifest_hash",
    {"axes": arr({"$ref": "#/$defs/parameter_axis"}, minimum=1), "joint_law": {"const": "INDEPENDENT_UNIFORM_FINITE_PRODUCT"}, "canonical_decode_algorithm_hash": H},
)
defs["entropy_source_contract"] = top(
    "ppc5.entropy_source_contract.v5", "contract_hash",
    {"source_kind": {"const": "PRECOMMITTED_IID_BYTE_STREAM"}, "acquisition_manifest_hash": H, "byte_model": {"const": "INDEPENDENT_UNIFORM_OCTETS"}, "addressing": {"const": "DISJOINT_SAMPLE_PROPOSAL_SLICES"}, "expansion_algorithm": {"const": "SHA256_COUNTER_EXPANSION_V1"}, "collision_policy": {"const": "RETAIN"}, "independence_scope": {"const": "REGISTERED_ENTROPY_MODEL_NOT_EMPIRICAL_PROOF"}},
)
defs["membership_gate_entry"] = closed(
    ["gate_id", "sample_ordinals", "lower_unit_key_schema_hash"],
    {"gate_id": SYM, "sample_ordinals": arr(integer(), minimum=1, unique=True), "lower_unit_key_schema_hash": H},
)
defs["pre_entropy_membership_manifest"] = top(
    "ppc5.pre_entropy_membership_manifest.v5", "manifest_hash",
    {"sample_size": integer(1), "entries": arr({"$ref": "#/$defs/membership_gate_entry"}, minimum=1), "fixed_before_entropy": {"const": True}, "content_selected_membership_forbidden": {"const": True}},
)
defs["common_seed_entry"] = closed(
    ["call_role", "call_ordinal", "seed"],
    {"call_role": SYM, "call_ordinal": integer(), "seed": integer()},
)
defs["common_seed_bundle"] = top(
    "ppc5.common_seed_bundle.v5", "bundle_hash",
    {"recipient_life_id": ID, "derivation_algorithm": {"const": "SHA256_DOMAIN_COUNTER_TO_UINT64_V1"}, "entries": arr({"$ref": "#/$defs/common_seed_entry"}, minimum=1), "shared_across_paired_arms": {"const": True}},
)
defs["gate_spec"] = closed(
    ["gate_ordinal", "gate_id", "assay_id", "gate_kind", "treatment_role", "control_role", "endpoint_id", "endpoint_lower", "endpoint_upper", "benefit_orientation", "margin", "pi0_or_ceiling", "alpha_threshold", "cp_tail_alpha", "membership_manifest_hash", "scientific_justification", "claim_fragment"],
    {"gate_ordinal": integer(), "gate_id": SYM, "assay_id": enum("D1A", "D1B", "D1C", "D1D"), "gate_kind": enum("SUPERIORITY", "SPECIFICITY", "TOTAL_POLICY", "SHAM_NONINFERIORITY", "SAFETY", "MISSINGNESS"), "treatment_role": NUL_SYM, "control_role": NUL_SYM, "endpoint_id": SYM, "endpoint_lower": RAT, "endpoint_upper": RAT, "benefit_orientation": SYM, "margin": RAT, "pi0_or_ceiling": PROB, "alpha_threshold": PROB, "cp_tail_alpha": PROB, "membership_manifest_hash": H, "scientific_justification": byte_ref("SCIENTIFIC_JUSTIFICATION", 0), "claim_fragment": byte_ref("CLAIM_FRAGMENT", 1)},
)
defs["gate_registry"] = top(
    "ppc5.gate_registry.v5", "registry_hash",
    {"membership_manifest_hash": H, "gates": arr({"$ref": "#/$defs/gate_spec"}, minimum=1), "expansion_complete": {"const": True}, "per_edge_averaging_forbidden": {"const": True}},
)
defs["generator_manifest"] = top(
    "ppc5.generator_manifest.v5", "manifest_hash",
    {
        "generator_name": SYM, "generator_version": BYTES,
        "source_manifest_hash": H, "pure_function_symbol": SYM,
        "ordinal_blind": {"const": True},
        "parameter_space_manifest_hash": H,
        "parameter_law": {"const": "UNIFORM_FINITE_PRODUCT"},
        "entropy_source_contract_hash": H,
        "entropy_expansion_algorithm": {"const": "SHA256_COUNTER_EXPANSION_V1"},
        "proposal_limit_per_life": integer(1),
        "acceptance_predicate_hash": H,
        "pre_entropy_membership_manifest_hash": H,
        "within_draw_donor_rule": {"const": "RECIPIENT_DISJOINT_EXACT_MATCH_INSIDE_DRAW"},
        "cross_draw_policy": {"const": "NO_REMATCH_NO_DEDUP_RETAIN_NATURAL_COLLISIONS"},
    },
)
defs["entropy_receipt"] = top(
    "ppc5.entropy_receipt.v5", "receipt_hash",
    {
        "source_contract_hash": H, "master_commitment_hash": H,
        "sample_ordinal": integer(), "proposal_ordinal": integer(),
        "slice_offset": integer(), "slice_length": integer(1),
        "entropy_raw_sha256": H,
        "collision_policy": {"const": "RETAIN"},
    },
)
defs["proposal_receipt"] = closed(
    ["proposal_ordinal", "entropy_receipt_hash", "candidate_bundle_hash", "status", "first_failure"],
    {
        "proposal_ordinal": integer(), "entropy_receipt_hash": H,
        "candidate_bundle_hash": H, "status": enum("ACCEPTED", "REJECTED"),
        "first_failure": NUL_SYM,
    },
)
defs["membership_entry"] = closed(
    ["gate_id", "sample_ordinal", "lower_unit_ids"],
    {"gate_id": SYM, "sample_ordinal": integer(), "lower_unit_ids": arr(ID, minimum=1, unique=True)},
)
defs["life_sample_receipt"] = top(
    "ppc5.life_sample_receipt.v5", "receipt_hash",
    {
        "generator_manifest_hash": H, "sample_ordinal": integer(),
        "proposals": arr({"$ref": "#/$defs/proposal_receipt"}, minimum=1),
        "accepted_proposal_ordinal": {"oneOf": [integer(), {"type": "null"}]},
        "recipient_bundle_hash": NUL_H, "donor_bundle_hash": NUL_H,
        "recipient_donor_disjointness_proof_hash": NUL_H,
        "gate_memberships": arr({"$ref": "#/$defs/membership_entry"}, minimum=1),
        "common_seed_bundle_hash": NUL_H,
        "status": enum("ACCEPTED", "PROPOSAL_EXHAUSTED"),
    },
)
defs["semantic_table"] = top(
    "ppc5.semantic_table.v5", "table_hash",
    {"table_id": ID, "candidates": arr({"$ref": "#/$defs/candidate"}, minimum=1)},
)
defs["assay_assignment"] = top(
    "ppc5.assay_assignment.v5", "assignment_hash",
    {
        "recipient_life_id": ID, "sample_ordinal": integer(), "assay_id": enum("D1A", "D1B", "D1C", "D1D"),
        "clone_id": ID, "opaque_instance_id": ID, "snapshot_hash": H,
        "seed_bundle_hash": H, "component_matrix_hash": H,
        "privileged_condition_code": SYM,
    },
)
defs["overlap_stratum"] = closed(
    ["dimension", "stratum_id", "acquire_count", "probe_count", "overlap_count"],
    {"dimension": enum("SEMANTIC_FAMILY", "ALIAS_FAMILY", "ITEM_FAMILY", "DONOR_GROUP", "EXACT_ACQUIRE_PROBE"), "stratum_id": ID, "acquire_count": integer(), "probe_count": integer(), "overlap_count": integer()},
)
defs["overlap_manifest"] = top(
    "ppc5.overlap_manifest.v5", "manifest_hash",
    {"generator_manifest_hash": H, "strata": arr({"$ref": "#/$defs/overlap_stratum"}, minimum=1), "descriptive_only": {"const": True}},
)
defs["construction_scope_receipt"] = top(
    "ppc5.construction_scope_receipt.v5", "receipt_hash",
    {
        "generator_manifest_hash": H, "life_sample_receipt_hashes": arr(H, minimum=1, unique=True),
        "all_samples_accepted": {"type": "boolean"},
        "power_scope": {"const": "CONDITIONAL_ON_SEALED_CONSTRUCTION"},
        "qualification_literal_hash": H,
        "status": enum("SEALED", "BLOCKED_PROPOSAL_EXHAUSTED", "BLOCKED_CONSTRUCTION"),
    },
)


# Path universe and per-edge interventions.
defs["graph_edge"] = closed(
    ["edge_id", "source_id", "target_id", "relation_id", "source_event_id", "source_event_preimage_hash"],
    {"edge_id": ID, "source_id": ID, "target_id": ID, "relation_id": ID, "source_event_id": ID, "source_event_preimage_hash": H},
)
defs["path_record"] = closed(
    ["path_ordinal", "path_template_id", "ordered_edge_ids", "oracle_input_hash", "oracle_output_action_id", "sufficient"],
    {"path_ordinal": integer(), "path_template_id": ID, "ordered_edge_ids": arr(ID, minimum=1, maximum=3), "oracle_input_hash": H, "oracle_output_action_id": NUL_ID, "sufficient": {"type": "boolean"}},
)
defs["path_suite_manifest"] = top(
    "ppc5.path_suite_manifest.v5", "manifest_hash",
    {"item_id": ID, "read_budget": integer(2, 3), "canonical_edges": arr({"$ref": "#/$defs/graph_edge"}, minimum=2), "all_simple_paths": arr({"$ref": "#/$defs/path_record"}, minimum=1), "selected_path_template_id": ID, "cross_item_source_disjointness_hash": H},
)
defs["subset_proof"] = closed(
    ["mask", "ordered_edge_ids", "oracle_input_hash", "oracle_output_action_id", "sufficient"],
    {"mask": integer(1), "ordered_edge_ids": arr(ID, minimum=1, maximum=2), "oracle_input_hash": H, "oracle_output_action_id": NUL_ID, "sufficient": {"const": False}},
)
defs["edge_intervention_proof"] = closed(
    ["edge_position", "edge_id", "source_event_id", "source_event_preimage_hash", "cut_receipt_hash", "twin_receipt_hash", "twin_reverses_edge", "sham_receipt_hash", "sham_preserves_action", "parity_receipt_hash"],
    {"edge_position": integer(), "edge_id": ID, "source_event_id": ID, "source_event_preimage_hash": H, "cut_receipt_hash": H, "twin_receipt_hash": H, "twin_reverses_edge": {"const": True}, "sham_receipt_hash": H, "sham_preserves_action": {"const": True}, "parity_receipt_hash": H},
)
defs["path_proof"] = top(
    "ppc5.path_proof.v5", "proof_hash",
    {"path_suite_manifest_hash": H, "item_id": ID, "path_template_id": ID, "path_length": integer(2, 3), "ordered_edge_ids": arr(ID, minimum=2, maximum=3), "proper_subset_proofs": arr({"$ref": "#/$defs/subset_proof"}, minimum=2, maximum=6), "full_set_oracle_input_hash": H, "full_set_action_id": ID, "alternate_path_proofs": arr({"$ref": "#/$defs/path_record"}), "edge_proofs": arr({"$ref": "#/$defs/edge_intervention_proof"}, minimum=2, maximum=3), "within_item_source_disjoint": {"const": True}},
)


# Public machine: one event type and a total closed vocabulary.
defs["public_view_body"] = closed(
    ["contract", "schema_version", "phase", "slot", "item_id", "world_bytes", "visible_record_refs", "opened_record_ids", "last_read", "live_prediction", "last_outcome", "budgets", "call_ordinal", "consecutive_error_count", "latest_error", "prior_public_summary", "legal_action_ids", "operation_schema_hash", "view_body_hash"],
    {"contract": {"const": "ppc5.public_view_body.v5"}, "schema_version": {"const": 5}, "phase": SYM, "slot": integer(), "item_id": ID, "world_bytes": byte_ref("WORLD_BYTES", 0), "visible_record_refs": arr(aref("VISIBLE_RECORD", ["BYTE_ARTIFACT_MANIFEST"])), "opened_record_ids": arr(ID, unique=True), "last_read": nullable({"$ref": "#/$defs/read_response"}), "live_prediction": nullable({"$ref": "#/$defs/prediction"}), "last_outcome": nullable({"$ref": "#/$defs/outcome"}), "budgets": {"$ref": "#/$defs/budget"}, "call_ordinal": integer(), "consecutive_error_count": integer(0, 2), "latest_error": NUL_SYM, "prior_public_summary": nullable(byte_ref("PRIOR_PUBLIC_SUMMARY", 0)), "legal_action_ids": arr(ID, minimum=1, unique=True), "operation_schema_hash": H, "view_body_hash": H},
)
defs["model_view"] = top(
    "ppc5.model_view.v5", "view_hash",
    {"public_view_body": {"$ref": "#/$defs/public_view_body"}, "ledger_head": H},
)
defs["controller_queue_entry"] = closed(
    ["slot", "slot_receipt_hash", "state"],
    {"slot": integer(), "slot_receipt_hash": H, "state": enum("QUEUED", "REJECTED", "FLUSHED", "DISCARDED")},
)
defs["private_controller_receipt"] = top(
    "ppc5.private_controller_receipt.v5", "controller_hash",
    {"assay_id": enum("D1A", "D1B", "D1C", "D1D"), "program": enum("DIRECT_PROVIDER", "D1B_AUTHENTIC", "D1B_ONE_SHOT", "D1B_OPEN_LOOP", "FIXED_BEHAVIOR", "D1D_TOTAL"), "opaque_instance_id": ID, "assignment_hash": H, "phase": SYM, "required_operation": enum("READ", "PREDICT", "ACT", "NONE"), "slot": integer(), "slot_limit": integer(), "accepted_read_count": integer(), "queue_slots": arr({"$ref": "#/$defs/controller_queue_entry"}), "next_flush_slot": integer(), "restricted_projection_hash": NUL_H, "model_manifest_hash": H, "tokenizer_manifest_hash": H, "prompt_manifest_hash": H, "common_seed_bundle_hash": H, "remaining_budget": {"$ref": "#/$defs/budget"}, "committed_prediction_envelope_hash": NUL_H, "committed_action_envelope_hash": NUL_H, "committed_action_id": NUL_ID, "terminal": {"type": "boolean"}},
)
defs["operation_envelope"] = top(
    "ppc5.operation_envelope.v5", "envelope_hash",
    {"call_id": ID, "call_ordinal": integer(), "model_manifest_hash": H, "tokenizer_manifest_hash": H, "prompt_bytes": nullable(byte_ref("PROMPT_BYTES", 0)), "adapter_manifest_hash": NUL_H, "seed": integer(), "input_tokens": integer(), "output_tokens": integer(), "raw_output": nullable(byte_ref("RAW_MODEL_OUTPUT", 0)), "parse_status": enum("PARSED", "MODEL_MISSING_NO_RETRY", "PARSE_ERROR", "TOKEN_LIMIT"), "operation": nullable({"$ref": "#/$defs/operation"})},
)
defs["operation_result"] = top(
    "ppc5.operation_result.v5", "result_hash",
    {"status": enum("READ_SUCCESS", "PREDICT_SUCCESS", "ACT_SUCCESS", "ERROR", "ERROR_LIMIT", "TERMINAL", "SLOT_ACK", "COMMIT_ACK", "FLUSH_SKIPPED_REJECTED", "PROVIDER_MISSING_NO_RETRY"), "origin": enum("MODEL", "HARNESS", "PROVIDER", "ENVIRONMENT", "CONTROLLER"), "read_response": nullable({"$ref": "#/$defs/read_response"}), "outcome": nullable({"$ref": "#/$defs/outcome"}), "error_code": NUL_SYM, "trigger_error_code": NUL_SYM, "stop_reason": NUL_SYM, "slot": {"oneOf": [integer(), {"type": "null"}]}, "ack_status": nullable(enum("QUEUED", "REJECTED", "COMMITTED"))},
)
defs["queue_slot_receipt"] = top(
    "ppc5.queue_slot_receipt.v5", "slot_hash",
    {"slot": integer(), "seed_ordinal": integer(), "state": enum("QUEUED", "REJECTED"), "controller_before_hash": H, "controller_after_hash": H, "operation_envelope_hash": H, "request_hash": NUL_H, "rejection_error": NUL_SYM},
)
defs["queue_effect_receipt"] = top(
    "ppc5.queue_effect_receipt.v5", "effect_hash",
    {"slot": integer(), "queued_slot_hash": H, "effect": enum("FLUSHED", "DISCARDED"), "provider_receipt_hash": NUL_H, "emission_receipt_hash": NUL_H, "public_result_hash": NUL_H, "public_transition_event_hash": NUL_H, "discard_reason": NUL_SYM, "controller_before_hash": H, "controller_after_hash": H},
)
defs["state_body"] = top(
    "ppc5.state_body.v5", "body_hash",
    {"state_id": ID, "state_ordinal": integer(), "phase": enum("INITIAL", "RUNNING", "TERMINAL"), "public_view_body": nullable({"$ref": "#/$defs/public_view_body"}), "private_controller_receipt_hash": H, "terminal": nullable({"$ref": "#/$defs/terminal_payload"})},
)
defs["transition_event"] = top(
    "ppc5.transition_event.v5", "event_hash",
    {"event_id": ID, "event_ordinal": integer(), "cause": enum("MODEL_DISPATCH", "DIRECT_PROVIDER", "CONTROLLER_PHASE", "QUEUE_FLUSH", "QUEUE_DISCARD", "COMMITTED_ACTION", "HARNESS_TERMINAL"), "prior_event_hash": H, "pre_state_receipt_hash": H, "operation_envelope_hash": NUL_H, "operation_result_hash": H, "controller_before_receipt_hash": H, "controller_after_receipt_hash": H, "lineage": arr({"$ref": "#/$defs/artifact_ref"}, minimum=1), "debit_before": {"$ref": "#/$defs/budget"}, "debit_after": {"$ref": "#/$defs/budget"}, "post_state_body_hash": H},
)
defs["state_receipt"] = top(
    "ppc5.state_receipt.v5", "state_receipt_hash",
    {"state_id": ID, "state_ordinal": integer(), "state_body_hash": H, "ledger_head": H},
)
defs["controller_row"] = closed(
    ["row_id", "assay_id", "program", "phase_pattern", "dispatch_kind", "required_operation", "accepted_result_classes", "first_failure_order", "debit", "queue_effect", "success_next_phase", "error_next_phase", "terminal_reason", "endpoint_effect"],
    {"row_id": SYM, "assay_id": enum("D1A", "D1B", "D1C", "D1D"), "program": SYM, "phase_pattern": BYTES, "dispatch_kind": enum("MODEL", "PROVIDER", "CONTROLLER", "ENVIRONMENT"), "required_operation": enum("READ", "PREDICT", "ACT", "NONE"), "accepted_result_classes": arr(SYM, minimum=1, unique=True), "first_failure_order": arr(SYM, minimum=1, unique=True), "debit": {"$ref": "#/$defs/budget"}, "queue_effect": enum("NONE", "QUEUE", "FLUSH", "DISCARD", "EXECUTE_COMMIT"), "success_next_phase": SYM, "error_next_phase": SYM, "terminal_reason": NUL_SYM, "endpoint_effect": enum("NONE", "SELECTION_OBSERVATION", "ACTION_OBSERVATION", "MISSING_OBSERVATION", "INTEGRITY_BLOCKER")},
)
defs["controller_registry"] = top(
    "ppc5.controller_registry.v5", "registry_hash",
    {"operation_vocabulary": arr(SYM, minimum=4, unique=True), "result_vocabulary": arr(SYM, minimum=10, unique=True), "terminal_vocabulary": arr(SYM, minimum=7, unique=True), "error_vocabulary": arr(SYM, minimum=10, unique=True), "first_failure_order": arr(SYM, minimum=10, unique=True), "rows": arr({"$ref": "#/$defs/controller_row"}, minimum=1)},
)


# Restricted provider/intervention surfaces: arm labels and scores are absent.
defs["provider_ingress"] = top(
    "ppc5.provider_ingress.v5", "ingress_hash",
    {"request_bytes": byte_ref("REQUEST_BYTES", 0), "semantic_table_hash": H, "tokenizer_manifest_hash": H, "scoring_kernel_manifest_hash": H, "scoring_algorithm": {"const": "MEAN_RESPONSE_LOGPROB_V5"}, "opaque_mount_handle": NUL_ID, "debit_class": SYM, "input_length_class": SYM},
)
defs["provider_receipt"] = top(
    "ppc5.provider_receipt.v5", "receipt_hash",
    {"ingress_hash": H, "scoring_algorithm": {"const": "MEAN_RESPONSE_LOGPROB_V5"}, "status": enum("FOUND", "NOT_FOUND", "PROVIDER_MISSING_NO_RETRY"), "public_response": {"$ref": "#/$defs/read_response"}, "public_response_bytes": byte_ref("PUBLIC_RESPONSE", 0), "debit_class": SYM, "output_length_class": SYM},
)
defs["provider_audit_receipt"] = top(
    "ppc5.provider_audit_receipt.v5", "receipt_hash",
    {"ingress_hash": H, "mounted_artifact_manifest_hash": NUL_H, "candidate_score_micros": arr({"type": "integer"}), "selected_candidate_id": NUL_ID, "scoring_kernel_hash": H, "diagnostics_bytes": byte_ref("PRIVATE_DIAGNOSTICS", 0), "public_provider_receipt_hash": H},
)
defs["descriptive_provider_ingress"] = top(
    "ppc5.descriptive_provider_ingress.v5", "ingress_hash",
    {"provider_algorithm": enum("RAW_RAG_V5", "FULL_CONTEXT_V5", "EXPLICIT_GRAPH_V5"), "request_bytes": byte_ref("REQUEST_BYTES", 0), "source_bytes": byte_ref("SOURCE_BYTES", 1), "opaque_mount_handle": NUL_ID, "debit_class": SYM},
)
defs["descriptive_provider_receipt"] = top(
    "ppc5.descriptive_provider_receipt.v5", "receipt_hash",
    {"ingress_hash": H, "provider_algorithm": enum("RAW_RAG_V5", "FULL_CONTEXT_V5", "EXPLICIT_GRAPH_V5"), "status": enum("FOUND", "NOT_FOUND", "PROVIDER_MISSING_NO_RETRY"), "public_response": {"$ref": "#/$defs/read_response"}, "public_response_bytes": byte_ref("PUBLIC_RESPONSE", 0), "debit_class": SYM},
)
defs["intervention_route_receipt"] = top(
    "ppc5.intervention_route_receipt.v5", "receipt_hash",
    {"assignment_hash": H, "path_template_id": ID, "edge_position": integer(), "edge_id": ID, "privileged_intervention_kind": enum("AUTHENTIC", "CUT", "TWIN", "SHAM"), "match_count": integer(), "selected_source_response_hash": NUL_H, "resolved_public_bytes": nullable(byte_ref("RESOLVED_PUBLIC_BYTES", 0)), "parity_receipt_hash": NUL_H, "status": enum("RESOLVED", "RUN_INVALID")},
)
defs["resolved_response_projection"] = top(
    "ppc5.resolved_response_projection.v5", "projection_hash",
    {"opaque_instance_id": ID, "resolved_public_bytes": byte_ref("RESOLVED_PUBLIC_BYTES", 0), "debit_class": SYM, "input_length_class": SYM, "output_length_class": SYM, "opaque_lineage_id": ID},
)
defs["intervention_emission_receipt"] = top(
    "ppc5.intervention_emission_receipt.v5", "receipt_hash",
    {"projection_hash": H, "opaque_instance_id": ID, "emitted_public_bytes": byte_ref("EMITTED_PUBLIC_BYTES", 0), "debit_class": SYM, "output_length_class": SYM, "opaque_lineage_id": ID},
)


# DREAM, reversible context, evidence, and SLEEP.
defs["dream_input"] = top(
    "ppc5.dream_input.v5", "input_hash",
    {"snapshot_hash": H, "public_slice": byte_ref("PUBLIC_SLICE", 0), "world_state": byte_ref("WORLD_STATE", 1), "live_prediction": nullable(byte_ref("LIVE_PREDICTION", 2)), "allowed_record_ids": arr(ID, unique=True), "capacity_records": integer(), "render_token_ceiling": integer(1), "shared_call_id": ID},
)
defs["dream_render"] = top(
    "ppc5.dream_render.v5", "render_hash",
    {"dream_input_hash": H, "prompt_bytes": byte_ref("DREAM_PROMPT", 0), "rendered_input_bytes": byte_ref("DREAM_RENDER", 1), "input_tokens": integer(), "model_manifest_hash": H, "tokenizer_manifest_hash": H, "seed": integer()},
)
defs["dream_publish"] = closed(
    ["kind", "retained_record_ids", "next_focus_record_id"],
    {"kind": {"const": "PUBLISH"}, "retained_record_ids": arr(ID, unique=True), "next_focus_record_id": NUL_ID},
)
defs["dream_abstain"] = closed(
    ["kind", "reason"], {"kind": {"const": "ABSTAIN"}, "reason": SYM},
)
defs["dream_result"] = {"oneOf": [{"$ref": "#/$defs/dream_publish"}, {"$ref": "#/$defs/dream_abstain"}]}
defs["dream_receipt"] = top(
    "ppc5.dream_receipt.v5", "receipt_hash",
    {"shared_call_id": ID, "dream_render_hash": H, "status": enum("VALID", "PUBLISH_EMPTY", "ABSTAIN", "DREAM_INVALID_OUTPUT", "DREAM_MISSING_NO_RETRY"), "raw_output": nullable(byte_ref("RAW_DREAM_OUTPUT", 0)), "result": nullable({"$ref": "#/$defs/dream_result"}), "input_tokens": integer(), "output_tokens": integer(), "debit_before": {"$ref": "#/$defs/budget"}, "debit_after": {"$ref": "#/$defs/budget"}},
)
defs["context_install_receipt"] = top(
    "ppc5.context_install_receipt.v5", "receipt_hash",
    {"opaque_instance_id": ID, "policy": enum("AUTHENTIC_DREAM_CONTEXT", "RECENCY_CONTEXT", "PERMUTED_CONTEXT"), "dependency_kind": enum("DREAM_BYTES", "SEALED_ELIGIBLE_UNIVERSE"), "dream_receipt_hash": NUL_H, "capacity_source": {"const": "RUN_LOCK_CONTEXT_CAPACITY"}, "ordered_record_ids": arr(ID, unique=True), "focus_record_id": NUL_ID, "rendered_context": nullable(byte_ref("INSTALLED_CONTEXT", 0)), "render_tokens": integer(), "status": enum("VALID", "VALID_EMPTY", "ABSTAIN", "DREAM_INVALID_OUTPUT", "DREAM_MISSING_NO_RETRY"), "installed": {"type": "boolean"}},
)
defs["eligibility_receipt"] = top(
    "ppc5.eligibility_receipt.v5", "receipt_hash",
    {"record_id": ID, "source_event_id": ID, "role": SYM, "dream_visible": {"type": "boolean"}, "item_closed": {"type": "boolean"}, "source_commit_ordinal": integer(), "before_boundary": {"type": "boolean"}, "probe_or_future": {"type": "boolean"}, "target_derived": {"type": "boolean"}, "source_channel": enum("ACQUIRE", "PROBE", "COGNITIVE", "DREAM", "SCORER", "POLICY_TARGET"), "direct_relation": {"type": "boolean"}, "source_hash": H, "eligible": {"type": "boolean"}, "first_failure": NUL_SYM, "equivalence_tuple_hash": H, "semantic_family_id": ID, "alias_family_id": ID, "item_family_id": ID, "donor_overlap_group": ID},
)
defs["nominee_universe_receipt"] = top(
    "ppc5.nominee_universe_receipt.v5", "receipt_hash",
    {"recipient_life_id": ID, "snapshot_hash": H, "eligibility_receipt_hashes": arr(H, minimum=1, unique=True), "eligible_record_ids": arr(ID, unique=True), "capacity_order_hash": H},
)
defs["evidence_projection_receipt"] = top(
    "ppc5.evidence_projection_receipt.v5", "receipt_hash",
    {"root_policy": enum("DREAM_TO_SLEEP", "RECENCY_TO_SLEEP", "HASH_PERMUTED_TO_SLEEP"), "dependency_kind": enum("DREAM_NOMINEES", "SEALED_ELIGIBLE_UNIVERSE"), "nominee_universe_hash": H, "dream_receipt_hash": NUL_H, "capacity_source": {"const": "RUN_LOCK_ROOT_CAPACITY"}, "ordered_nominee_ids": arr(ID, unique=True), "projection_receipt_hashes": arr(H, unique=True)},
)
defs["root_selection_receipt"] = top(
    "ppc5.root_selection_receipt.v5", "receipt_hash",
    {"evidence_projection_hash": H, "root_policy": enum("DREAM_TO_SLEEP", "RECENCY_TO_SLEEP", "HASH_PERMUTED_TO_SLEEP"), "selected_representative_ids": arr(ID, unique=True), "status": enum("ROOTS_ADMITTED", "NO_ROOTS_SELECTED", "NO_ADMITTED_ROOTS", "DREAM_MISSING_NO_RETRY", "RUN_INVALID"), "first_blocker": NUL_SYM},
)
defs["sleep_row"] = top(
    "ppc5.sleep_row.v5", "row_hash",
    {"row_id": ID, "root_record_id": ID, "request_subject_id": ID, "request_relation_id": ID, "target_response": {"$ref": "#/$defs/read_response"}, "source_event_hash": H, "source_public_bytes": byte_ref("SOURCE_PUBLIC_BYTES", 0), "rendered_row_bytes": byte_ref("TRAINING_ROW", 1), "row_token_count": integer(1), "byte_length_class": SYM},
)
defs["corpus_manifest"] = top(
    "ppc5.corpus_manifest.v5", "manifest_hash",
    {"root_selection_hash": H, "status": enum("VALID", "VALID_EMPTY", "RUN_INVALID"), "row_refs": arr(aref("SLEEP_ROW", ["SLEEP_ROW"])), "corpus_bytes": byte_ref("CORPUS_BYTES", 0), "row_count": integer(), "token_count": integer(), "ordered_token_counts": arr(integer()), "ordered_byte_classes": arr(SYM)},
)
defs["trainer_execution_receipt"] = top(
    "ppc5.trainer_execution_receipt.v5", "receipt_hash",
    {"corpus_manifest_hash": H, "base_manifest_hash": H, "tokenizer_manifest_hash": H, "recipe_manifest_hash": H, "status": enum("SUCCEEDED", "SKIPPED_EMPTY", "FAILED"), "actual_rows": integer(), "actual_tokens": integer(), "actual_updates": integer(), "output_adapter_manifest_hash": NUL_H, "log_bytes": nullable(byte_ref("TRAINER_LOG", 0)), "exit_code": {"oneOf": [{"type": "integer"}, {"type": "null"}]}, "failure_reason": NUL_SYM},
)
defs["adapter_validation_receipt"] = top(
    "ppc5.adapter_validation_receipt.v5", "receipt_hash",
    {"trainer_receipt_hash": H, "status": enum("VALID", "VALID_EMPTY", "TRAIN_FAILED", "RUN_INVALID"), "adapter_manifest_hash": NUL_H, "base_hash_match": {"type": "boolean"}, "tokenizer_hash_match": {"type": "boolean"}, "shape_hash_match": {"type": "boolean"}, "finite_tensors": {"type": "boolean"}, "structural_check_passed": {"type": "boolean"}, "failure_reason": NUL_SYM},
)
defs["adapter_manifest"] = top(
    "ppc5.adapter_manifest.v5", "manifest_hash",
    {"artifact_id": ID, "byte_artifact_manifest_hash": NUL_H, "status": enum("VALID", "VALID_EMPTY", "TRAIN_FAILED", "RUN_INVALID"), "base_hash": H, "tokenizer_hash": H, "shape_hash": H, "recipe_family_hash": H, "mount_interface_hash": H, "corpus_hash": H, "row_count": integer(), "token_count": integer(), "update_count": integer(), "rank": integer(), "finite_tensors": {"type": "boolean"}, "structural_check_passed": {"type": "boolean"}},
)
defs["publication_receipt"] = top(
    "ppc5.publication_receipt.v5", "receipt_hash",
    {"validation_receipt_hash": H, "status": enum("PUBLISHED", "NOT_ATTEMPTED_EMPTY", "NOT_ATTEMPTED_FAILED", "RUN_INVALID"), "temporary_manifest_hash": NUL_H, "final_manifest_hash": NUL_H, "atomic_rename_receipt_hash": NUL_H, "failure_reason": NUL_SYM},
)


# Exact observations, gate inference, power, and release.
defs["stage_outcome"] = top(
    "ppc5.stage_outcome.v5", "receipt_hash",
    {"recipient_life_id": ID, "assay_id": enum("D1A", "D1B", "D1C", "D1D"), "opaque_instance_id": ID, "endpoint_id": SYM, "terminal_class": SYM, "raw_result_code": SYM, "raw_value": NUL_RAT, "analysis_value": NUL_RAT, "missing": {"type": "boolean"}, "claim_blocker": {"type": "boolean"}, "cause_event_refs": arr(aref("CAUSE_EVENT", ["TRANSITION_EVENT"]))},
)
defs["observation"] = top(
    "ppc5.observation.v5", "observation_hash",
    {"recipient_life_id": ID, "sample_ordinal": integer(), "assay_id": enum("D1A", "D1B", "D1C", "D1D"), "opaque_instance_id": ID, "unit_id": ID, "endpoint_id": SYM, "raw_value": NUL_RAT, "analysis_value": NUL_RAT, "missing": {"type": "boolean"}, "stage_outcome_hash": H},
)
defs["gate_observation_ref"] = closed(
    ["sample_ordinal", "treatment_observation_hash", "control_observation_hash", "paired_difference", "success", "missing"],
    {"sample_ordinal": integer(), "treatment_observation_hash": H, "control_observation_hash": H, "paired_difference": NUL_RAT, "success": {"type": "boolean"}, "missing": {"type": "boolean"}},
)
defs["paired_gate_result"] = top(
    "ppc5.paired_gate_result.v5", "receipt_hash",
    {"run_lock_hash": H, "generator_manifest_hash": H, "gate_id": SYM, "gate_kind": enum("SUPERIORITY", "SPECIFICITY", "TOTAL_POLICY", "SHAM_NONINFERIORITY"), "treatment_role": SYM, "control_role": SYM, "endpoint_id": SYM, "membership_hash": H, "observations": arr({"$ref": "#/$defs/gate_observation_ref"}, minimum=1), "N": integer(1), "successes": integer(), "margin": RAT, "pi0": PROB, "alpha_threshold": PROB, "cp_tail_alpha": PROB, "tail_probability": PROB, "cp_lower_bracket": {"$ref": "#/$defs/rational_bracket"}, "observed_rate": PROB, "missingness_result_hash": H, "decision": enum("PASS", "FAIL")},
)
defs["adverse_observation_ref"] = closed(
    ["sample_ordinal", "observation_hash", "adverse", "missing"],
    {"sample_ordinal": integer(), "observation_hash": H, "adverse": {"type": "boolean"}, "missing": {"type": "boolean"}},
)
defs["one_sample_safety_result"] = top(
    "ppc5.one_sample_safety_result.v5", "receipt_hash",
    {"run_lock_hash": H, "generator_manifest_hash": H, "gate_id": SYM, "endpoint_id": enum("FALSE_SELECTION", "NOT_FOUND"), "membership_hash": H, "designated_trials": arr({"$ref": "#/$defs/adverse_observation_ref"}, minimum=1), "N": integer(1), "adverse_events": integer(), "ceiling": PROB, "alpha_threshold": PROB, "cp_tail_alpha": PROB, "tail_probability": PROB, "cp_upper_bracket": {"$ref": "#/$defs/rational_bracket"}, "observed_rate": PROB, "missingness_result_hash": H, "decision": enum("PASS", "FAIL")},
)
defs["missingness_result"] = top(
    "ppc5.missingness_result.v5", "receipt_hash",
    {"run_lock_hash": H, "generator_manifest_hash": H, "gate_id": SYM, "opaque_instance_role": SYM, "endpoint_id": SYM, "membership_hash": H, "observations": arr({"$ref": "#/$defs/adverse_observation_ref"}, minimum=1), "N": integer(1), "missing_events": integer(), "ceiling": PROB, "alpha_threshold": PROB, "cp_tail_alpha": PROB, "tail_probability": PROB, "cp_upper_bracket": {"$ref": "#/$defs/rational_bracket"}, "observed_rate": PROB, "decision": enum("PASS", "FAIL")},
)
defs["gate_power_result"] = top(
    "ppc5.gate_power_result.v5", "receipt_hash",
    {"run_lock_hash": H, "gate_id": SYM, "gate_type": enum("PAIRED", "SAFETY", "MISSINGNESS"), "N": integer(1), "null_parameter": PROB, "worst_case_parameter": PROB, "margin_or_ceiling": RAT, "alpha_threshold": PROB, "cp_tail_alpha": PROB, "critical_counts": arr(integer(), unique=True), "full_release_conjunction_hash": H, "power": PROB, "construction_conditioned": {"const": True}},
)
defs["power_receipt"] = top(
    "ppc5.power_receipt.v5", "receipt_hash",
    {"run_lock_hash": H, "construction_scope_hash": H, "scope": {"const": "CONDITIONAL_ON_SEALED_CONSTRUCTION"}, "gate_power_result_refs": arr(aref("GATE_POWER_RESULT", ["GATE_POWER_RESULT"]), minimum=1), "union_lower_bound": PROB, "minimum_familywise_power": PROB, "decision": enum("PASS", "FAIL")},
)
defs["resource_entry"] = closed(
    ["stage_id", "event_id", "model_calls", "input_tokens", "output_tokens", "training_rows", "training_tokens", "updates", "adapter_rank", "adapter_bytes", "wall_micros", "gpu_micros", "energy_microjoules", "cost_microunits"],
    {"stage_id": SYM, "event_id": ID, "model_calls": integer(), "input_tokens": integer(), "output_tokens": integer(), "training_rows": integer(), "training_tokens": integer(), "updates": integer(), "adapter_rank": integer(), "adapter_bytes": integer(), "wall_micros": integer(), "gpu_micros": integer(), "energy_microjoules": {"oneOf": [integer(), {"type": "null"}]}, "cost_microunits": {"oneOf": [integer(), {"type": "null"}]}},
)
defs["resource_receipt"] = top(
    "ppc5.resource_receipt.v5", "receipt_hash",
    {"accounting_mode": enum("DIRECT", "SHARED_SPLIT_EQUAL"), "recipient_life_id": ID, "opaque_instance_id": ID, "entries": arr({"$ref": "#/$defs/resource_entry"}), "derivation_hashes": arr(H, unique=True)},
)
defs["assay_result"] = top(
    "ppc5.assay_result.v5", "result_hash",
    {"assay_id": enum("D1A", "D1B", "D1C", "D1D"), "claim_id": SYM, "gate_result_refs": arr(aref("GATE_RESULT", ["PAIRED_GATE_RESULT", "ONE_SAMPLE_SAFETY_RESULT", "MISSINGNESS_RESULT"]), minimum=1), "assay_p_value": PROB, "all_directions_passed": {"type": "boolean"}, "all_local_tests_passed": {"type": "boolean"}, "blocked": {"type": "boolean"}, "first_blocker": NUL_SYM},
)
defs["holm_result"] = top(
    "ppc5.holm_result.v5", "result_hash",
    {"alpha": PROB, "ordered_assay_refs": exact_refs(("D1A", ["ASSAY_RESULT"]), ("D1B", ["ASSAY_RESULT"]), ("D1C", ["ASSAY_RESULT"]), ("D1D", ["ASSAY_RESULT"])), "ordered_p_values": arr(PROB, minimum=4, maximum=4), "rejected_claim_ids": arr(SYM, unique=True), "stopped_at_index": {"oneOf": [integer(0, 3), {"type": "null"}]}, "all_four_rejected": {"type": "boolean"}},
)
defs["dependency_entry"] = closed(
    ["role", "ordinal", "artifact_type", "artifact_hash"],
    {"role": SYM, "ordinal": integer(), "artifact_type": SYM, "artifact_hash": H},
)
defs["dependency_map_receipt"] = top(
    "ppc5.dependency_map_receipt.v5", "receipt_hash",
    {"claim_id": SYM, "candidate_stage_only": {"const": True}, "ordered_dependencies": arr({"$ref": "#/$defs/dependency_entry"}, minimum=1), "dependency_registry_hash": H, "all_present_and_passing": {"type": "boolean"}, "first_blocker": NUL_SYM},
)

claim_map = {item["claim_id"]: item["release_text"] for item in CLAIMS["claims"]}
claim_map[CLAIMS["intersection"]["claim_id"]] = CLAIMS["intersection"]["release_text"]
claim_branches = []
release_branches = []
for claim_id, literal in claim_map.items():
    claim_branches.append({
        "properties": {"claim_id": {"const": claim_id}, "decision": {"const": "ELIGIBLE"}, "candidate_release_text": {"const": literal}, "first_blocker": {"type": "null"}}
    })
    claim_branches.append({
        "properties": {"claim_id": {"const": claim_id}, "decision": {"const": "BLOCKED"}, "candidate_release_text": {"type": "null"}, "first_blocker": SYM}
    })
    release_branches.append({
        "properties": {"claim_id": {"const": claim_id}, "status": {"const": "RELEASED"}, "release_text": {"const": literal}, "first_blocker": {"type": "null"}}
    })
    release_branches.append({
        "properties": {"claim_id": {"const": claim_id}, "status": {"const": "BLOCKED"}, "release_text": {"type": "null"}, "first_blocker": SYM}
    })
defs["claim_decision_receipt"] = top(
    "ppc5.claim_decision_receipt.v5", "receipt_hash",
    {"claim_id": SYM, "decision": enum("ELIGIBLE", "BLOCKED"), "candidate_release_text": nullable(BYTES), "qualification_text": {"const": CLAIMS["fixed_qualification"]}, "forbidden_claims": {"const": CLAIMS["forbidden_claims"]}, "dependency_receipt_hash": H, "first_blocker": NUL_SYM},
    one_of=claim_branches,
)
defs["claim_release_package"] = top(
    "ppc5.claim_release_package.v5", "package_hash",
    {"claim_id": SYM, "status": enum("RELEASED", "BLOCKED"), "release_text": nullable(BYTES), "qualification_text": {"const": CLAIMS["fixed_qualification"]}, "forbidden_claims": {"const": CLAIMS["forbidden_claims"]}, "candidate_decision_hash": H, "t14_receipt_hash": H, "preclaim_authority_hash": H, "dependency_map_hash": H, "overlap_manifest_hash": H, "construction_scope_hash": H, "evidence_manifest_hash": H, "first_blocker": NUL_SYM},
    one_of=release_branches,
)


# Acceptance evidence. PASS is a reducer output over materialized evidence.
defs["implementation_identity_receipt"] = top(
    "ppc5.implementation_identity_receipt.v5", "receipt_hash",
    {"implementation_id": ID, "source_manifest_hash": H, "root_algorithm_source_hash": H, "language_runtime_hash": H, "build_recipe_hash": H, "executable_hash": H},
)
defs["implementation_independence_receipt"] = top(
    "ppc5.implementation_independence_receipt.v5", "receipt_hash",
    {"implementation_a_hash": H, "implementation_b_hash": H, "distinct_ids": {"const": True}, "distinct_executables": {"const": True}, "distinct_root_algorithm_sources": {"const": True}, "shared_dependency_refs": arr({"$ref": "#/$defs/artifact_ref"})},
)
defs["fixture_case"] = top(
    "ppc5.fixture_case.v5", "case_hash",
    {"test_id": SYM, "ordinal": integer(), "case_id": ID, "input_refs": arr({"$ref": "#/$defs/artifact_ref"}, minimum=1), "expected_output_ref": nullable(aref("EXPECTED_OUTPUT")), "expected_failure_code": NUL_SYM},
)
defs["negative_mutation"] = top(
    "ppc5.negative_mutation.v5", "mutation_hash",
    {"test_id": SYM, "ordinal": integer(), "mutation_id": ID, "case_hash": H, "field_path": BYTES, "before_hash": H, "after_hash": H, "expected_failure_code": SYM, "allowed_changed_roles": arr(SYM, unique=True)},
)
defs["fixture_universe_manifest"] = top(
    "ppc5.fixture_universe_manifest.v5", "manifest_hash",
    {"test_id": SYM, "declared_stage": enum("PRE_RATIFICATION_GENERIC_INTAKE", "POST_RATIFICATION_PRE_MODEL", "PRE_MODEL_EXECUTION", "PRE_SCIENTIFIC_CLAIM"), "generator_name": SYM, "generator_version": BYTES, "generator_source_hash": H, "coverage_mode": enum("ENUMERATED", "GENERATED_PROVEN_COMPLETE"), "coverage_axes": arr(SYM, minimum=1, unique=True), "expected_case_count": integer(1), "case_refs": arr(aref("FIXTURE_CASE", ["FIXTURE_CASE"]), minimum=1), "mutation_refs": arr(aref("NEGATIVE_MUTATION", ["NEGATIVE_MUTATION"]), minimum=1), "prerequisite_refs": arr({"$ref": "#/$defs/artifact_ref"}), "evidence_role_registry_hash": H, "reduction_algorithm_hash": H, "completeness_proof": nullable(byte_ref("COMPLETENESS_PROOF", 0))},
)
defs["case_result"] = top(
    "ppc5.case_result.v5", "result_hash",
    {"test_id": SYM, "case_hash": H, "implementation_identity_hash": H, "expected_output_hash": NUL_H, "actual_output_hash": NUL_H, "expected_failure_code": NUL_SYM, "actual_failure_code": NUL_SYM, "matched": {"type": "boolean"}},
)
defs["mutation_result"] = top(
    "ppc5.mutation_result.v5", "result_hash",
    {"test_id": SYM, "mutation_hash": H, "implementation_identity_hash": H, "expected_failure_code": SYM, "actual_failure_code": NUL_SYM, "matched": {"type": "boolean"}},
)
defs["test_coverage_receipt"] = top(
    "ppc5.test_coverage_receipt.v5", "receipt_hash",
    {"test_id": SYM, "fixture_manifest_hash": H, "implementation_refs": arr(aref("IMPLEMENTATION", ["IMPLEMENTATION_IDENTITY_RECEIPT"]), minimum=1, maximum=2), "case_result_refs": arr(aref("CASE_RESULT", ["CASE_RESULT"]), minimum=1), "mutation_result_refs": arr(aref("MUTATION_RESULT", ["MUTATION_RESULT"]), minimum=1), "expected_count": integer(1), "executed_count": integer(), "missing_count": integer(), "extra_count": integer(), "duplicate_count": integer(), "mismatch_count": integer(), "independence_receipt_hash": NUL_H, "status": enum("PASS", "FAIL"), "derivation_algorithm_hash": H},
    one_of=[
        {
            "properties": {
                "test_id": {"const": "PPC5R5_T01"},
                "implementation_refs": exact_refs(("IMPLEMENTATION", ["IMPLEMENTATION_IDENTITY_RECEIPT"])),
                "independence_receipt_hash": {"type": "null"},
            }
        },
        {
            "properties": {
                "test_id": {"enum": [f"PPC5R5_T{i:02d}" for i in range(2, 15)]},
                "implementation_refs": exact_refs(
                    ("IMPLEMENTATION_A", ["IMPLEMENTATION_IDENTITY_RECEIPT"]),
                    ("IMPLEMENTATION_B", ["IMPLEMENTATION_IDENTITY_RECEIPT"]),
                ),
                "independence_receipt_hash": H,
            }
        },
    ],
)
defs["test_result"] = top(
    "ppc5.test_result.v5", "result_hash",
    {"test_id": SYM, "declared_stage": enum("PRE_RATIFICATION_GENERIC_INTAKE", "POST_RATIFICATION_PRE_MODEL", "PRE_MODEL_EXECUTION", "PRE_SCIENTIFIC_CLAIM"), "fixture_manifest_hash": H, "coverage_receipt_hash": H, "evidence_refs": arr({"$ref": "#/$defs/artifact_ref"}, minimum=1), "status": enum("PASS", "FAIL"), "first_failure": NUL_SYM},
    one_of=[
        {"properties": {"test_id": {"const": "PPC5R5_T01"}, "declared_stage": {"const": "PRE_RATIFICATION_GENERIC_INTAKE"}, "status": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"test_id": {"const": "PPC5R5_T01"}, "declared_stage": {"const": "PRE_RATIFICATION_GENERIC_INTAKE"}, "status": {"const": "FAIL"}, "first_failure": SYM}},
        {"properties": {"test_id": {"enum": [f"PPC5R5_T{i:02d}" for i in range(2, 13)]}, "declared_stage": {"const": "POST_RATIFICATION_PRE_MODEL"}, "status": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"test_id": {"enum": [f"PPC5R5_T{i:02d}" for i in range(2, 13)]}, "declared_stage": {"const": "POST_RATIFICATION_PRE_MODEL"}, "status": {"const": "FAIL"}, "first_failure": SYM}},
        {"properties": {"test_id": {"const": "PPC5R5_T13"}, "declared_stage": {"const": "PRE_MODEL_EXECUTION"}, "status": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"test_id": {"const": "PPC5R5_T13"}, "declared_stage": {"const": "PRE_MODEL_EXECUTION"}, "status": {"const": "FAIL"}, "first_failure": SYM}},
        {"properties": {"test_id": {"const": "PPC5R5_T14"}, "declared_stage": {"const": "PRE_SCIENTIFIC_CLAIM"}, "status": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"test_id": {"const": "PPC5R5_T14"}, "declared_stage": {"const": "PRE_SCIENTIFIC_CLAIM"}, "status": {"const": "FAIL"}, "first_failure": SYM}},
    ],
)
defs["endpoint_coverage_receipt"] = top(
    "ppc5.endpoint_coverage_receipt.v5", "receipt_hash",
    {"gate_registry_hash": H, "expected_endpoint_keys_hash": H, "observed_endpoint_keys_hash": H, "missing_keys": arr(BYTES), "extra_keys": arr(BYTES), "duplicate_keys": arr(BYTES), "status": enum("PASS", "FAIL")},
    one_of=[
        {"properties": {"status": {"const": "PASS"}, "missing_keys": {"maxItems": 0}, "extra_keys": {"maxItems": 0}, "duplicate_keys": {"maxItems": 0}}},
        {"properties": {"status": {"const": "FAIL"}}},
    ],
)


# Run lock and stage-specific authority. There is no generic authority schema.
defs["populated_run_lock"] = top(
    "ppc5.populated_run_lock.v5", "run_lock_hash",
    {
        "generator_manifest_ref": aref("GENERATOR_MANIFEST", ["GENERATOR_MANIFEST"], 0),
        "construction_scope_ref": aref("CONSTRUCTION_SCOPE", ["CONSTRUCTION_SCOPE_RECEIPT"], 0),
        "life_sample_refs": arr(aref("LIFE_SAMPLE", ["LIFE_SAMPLE_RECEIPT"]), minimum=1, unique=True),
        "sample_size": integer(1),
        "gate_registry_ref": aref("GATE_REGISTRY", ["GATE_REGISTRY"], 0),
        "controller_registry_ref": aref("CONTROLLER_REGISTRY", ["CONTROLLER_REGISTRY"], 0),
        "path_suite_manifest_refs": arr(aref("PATH_SUITE", ["PATH_SUITE_MANIFEST"]), minimum=1, unique=True),
        "semantic_table_refs": arr(aref("SEMANTIC_TABLE", ["SEMANTIC_TABLE"]), minimum=1, unique=True),
        "context_capacity": integer(), "root_capacity": integer(), "behavior_read_slots": integer(), "direct_request_count": integer(1),
        "model_manifest_ref": aref("MODEL_MANIFEST", ["BYTE_ARTIFACT_MANIFEST"], 0),
        "tokenizer_manifest_ref": aref("TOKENIZER_MANIFEST", ["BYTE_ARTIFACT_MANIFEST"], 0),
        "embedding_manifest_ref": nullable(aref("EMBEDDING_MANIFEST", ["BYTE_ARTIFACT_MANIFEST"], 0)),
        "trainer_recipe_ref": aref("TRAINER_RECIPE", ["BYTE_ARTIFACT_MANIFEST"], 0),
        "writer_algorithm_ref": aref("WRITER_ALGORITHM", ["BYTE_ARTIFACT_MANIFEST"], 0),
        "provider_algorithm": {"const": "MEAN_RESPONSE_LOGPROB_V5"},
        "alpha": PROB, "cp_tail_alpha": PROB, "minimum_familywise_power": PROB,
        "test_fixture_refs": exact_refs(*[(f"T{index:02d}", ["FIXTURE_UNIVERSE_MANIFEST"]) for index in range(1, 15)]),
        "allowed_dispatch_manifest_ref": aref("ALLOWED_DISPATCH_MANIFEST", ["BYTE_ARTIFACT_MANIFEST"], 0),
        "forbidden_scope_ref": aref("FORBIDDEN_SCOPE", ["BYTE_ARTIFACT_MANIFEST"], 0),
        "all_fields_populated": {"const": True},
    },
)
defs["static_seal_receipt"] = top(
    "ppc5.static_seal_receipt.v5", "receipt_hash",
    {"sealer_id": ID, "sealer_implementation_hash": H, "run_lock_hash": H, "conformance_receipt_hash": H, "construction_output_manifest_hash": H, "output_refs": arr(aref("SEALED_CONSTRUCTION_OUTPUT", ["BYTE_ARTIFACT_MANIFEST"]), minimum=1), "decision": enum("PASS", "FAIL"), "first_failure": NUL_SYM},
    one_of=[
        {"properties": {"decision": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"decision": {"const": "FAIL"}, "first_failure": SYM}},
    ],
)
defs["sealer_independence_receipt"] = top(
    "ppc5.sealer_independence_receipt.v5", "receipt_hash",
    {"seal_a_hash": H, "seal_b_hash": H, "implementation_independence_hash": H, "role_for_role_outputs_equal": {"type": "boolean"}, "decision": enum("PASS", "FAIL"), "first_failure": NUL_SYM},
    one_of=[
        {"properties": {"decision": {"const": "PASS"}, "role_for_role_outputs_equal": {"const": True}, "first_failure": {"type": "null"}}},
        {"properties": {"decision": {"const": "FAIL"}, "first_failure": SYM}},
    ],
)
defs["independent_review_receipt"] = top(
    "ppc5.independent_review_receipt.v5", "receipt_hash",
    {"reviewer_id": ID, "reviewer_context_manifest_hash": H, "run_lock_hash": H, "seal_independence_hash": H, "read_only_evidence_manifest_hash": H, "verdict": enum("PASS", "FAIL"), "concern_refs": arr(byte_ref("REVIEW_CONCERN")), "review_bytes": byte_ref("REVIEW_BYTES", 0)},
    one_of=[
        {"properties": {"verdict": {"const": "PASS"}, "concern_refs": {"maxItems": 0}}},
        {"properties": {"verdict": {"const": "FAIL"}, "concern_refs": {"minItems": 1}}},
    ],
)
defs["advocate_receipt"] = top(
    "ppc5.advocate_receipt.v5", "receipt_hash",
    {"review_receipt_hash": H, "position": enum("ACCEPT_REVIEW", "REQUEST_REWORK", "EXPLAIN_WITHOUT_OVERRIDE"), "response_bytes": byte_ref("ADVOCATE_RESPONSE", 0), "override_capability": {"const": False}},
)
defs["architecture_ratification_receipt"] = top(
    "ppc5.architecture_ratification_receipt.v5", "receipt_hash",
    {"stage": {"const": "PRE_RATIFICATION_SPECIFICATION"}, "predecessor_receipt_hash": {"type": "null"}, "subject_refs": exact_refs(("ARCHITECTURE_CHANGE", ["ARCHITECTURE_CHANGE"]), ("INTERPRETATION_SYSTEMS", ["ARCHITECTURE_INTERPRETATION"]), ("INTERPRETATION_SCIENCE", ["ARCHITECTURE_INTERPRETATION"]), ("CRITIQUE", ["ARCHITECTURE_CRITIQUE"]), ("CONSENSUS", ["ARCHITECTURE_CONSENSUS"]), ("SCOPE_PROPOSAL", ["SCOPE_PROPOSAL"]), ("T01_GENERIC", ["TEST_RESULT"])), "authorized_scope": arr(BYTES, minimum=1, unique=True), "forbidden_scope": arr(BYTES, unique=True), "decision": enum("PASS", "FAIL"), "model_execution_reachable": {"const": False}, "human_evidence": {"$ref": "#/$defs/human_evidence"}, "denial_reason": NUL_SYM},
    one_of=[{"properties": {"decision": {"const": "PASS"}, "denial_reason": {"type": "null"}}}, {"properties": {"decision": {"const": "FAIL"}, "denial_reason": SYM}}],
)
defs["conformance_receipt"] = top(
    "ppc5.conformance_receipt.v5", "receipt_hash",
    {"stage": {"const": "POST_RATIFICATION_PRE_MODEL"}, "predecessor_receipt_hash": H, "subject_refs": exact_refs(("ARCHITECTURE_RATIFICATION", ["ARCHITECTURE_RATIFICATION_RECEIPT"]), ("IMPLEMENTATION_A", ["IMPLEMENTATION_IDENTITY_RECEIPT"]), ("IMPLEMENTATION_B", ["IMPLEMENTATION_IDENTITY_RECEIPT"]), ("IMPLEMENTATION_INDEPENDENCE", ["IMPLEMENTATION_INDEPENDENCE_RECEIPT"]), *[(f"T{index:02d}", ["TEST_RESULT"]) for index in range(2, 13)], ("INVENTORY_SCHEMA_COVERAGE", ["TEST_COVERAGE_RECEIPT"])), "authorized_scope": arr(BYTES, minimum=1, unique=True), "forbidden_scope": arr(BYTES, unique=True), "decision": enum("PASS", "FAIL"), "model_execution_reachable": {"const": False}, "human_evidence": {"type": "null"}, "denial_reason": NUL_SYM},
    one_of=[{"properties": {"decision": {"const": "PASS"}, "denial_reason": {"type": "null"}}}, {"properties": {"decision": {"const": "FAIL"}, "denial_reason": SYM}}],
)
defs["human_run_ratification_receipt"] = top(
    "ppc5.human_run_ratification_receipt.v5", "receipt_hash",
    {"subject_refs": exact_refs(("RUN_LOCK", ["POPULATED_RUN_LOCK"]), ("CONFORMANCE", ["CONFORMANCE_RECEIPT"]), ("STATIC_SEAL_A", ["STATIC_SEAL_RECEIPT"]), ("STATIC_SEAL_B", ["STATIC_SEAL_RECEIPT"]), ("SEALER_INDEPENDENCE", ["SEALER_INDEPENDENCE_RECEIPT"]), ("FRESH_REVIEW", ["INDEPENDENT_REVIEW_RECEIPT"]), ("ADVOCATE", ["ADVOCATE_RECEIPT"]), ("T01_T13_MANIFEST", ["BYTE_ARTIFACT_MANIFEST"])), "authorized_scope": arr(BYTES, minimum=1, unique=True), "forbidden_scope": arr(BYTES, unique=True), "decision": enum("PASS", "FAIL"), "human_evidence": {"$ref": "#/$defs/human_evidence"}, "denial_reason": NUL_SYM},
    one_of=[
        {"properties": {"decision": {"const": "PASS"}, "denial_reason": {"type": "null"}}},
        {"properties": {"decision": {"const": "FAIL"}, "denial_reason": SYM}},
    ],
)
defs["pre_model_authority_receipt"] = top(
    "ppc5.pre_model_authority_receipt.v5", "receipt_hash",
    {"stage": {"const": "PRE_MODEL_EXECUTION"}, "predecessor_receipt_hash": H, "subject_refs": exact_refs(("RUN_LOCK", ["POPULATED_RUN_LOCK"]), ("CONFORMANCE", ["CONFORMANCE_RECEIPT"]), *[(f"T{index:02d}", ["TEST_RESULT"]) for index in range(1, 14)], ("STATIC_SEAL_A", ["STATIC_SEAL_RECEIPT"]), ("STATIC_SEAL_B", ["STATIC_SEAL_RECEIPT"]), ("SEALER_INDEPENDENCE", ["SEALER_INDEPENDENCE_RECEIPT"]), ("FRESH_REVIEW", ["INDEPENDENT_REVIEW_RECEIPT"]), ("ADVOCATE", ["ADVOCATE_RECEIPT"]), ("POWER", ["POWER_RECEIPT"]), ("HUMAN_RUN_RATIFICATION", ["HUMAN_RUN_RATIFICATION_RECEIPT"])), "decision": enum("PASS", "FAIL"), "model_execution_reachable": {"type": "boolean"}, "human_evidence": {"type": "null"}, "denial_reason": NUL_SYM},
    one_of=[{"properties": {"decision": {"const": "PASS"}, "model_execution_reachable": {"const": True}, "denial_reason": {"type": "null"}}}, {"properties": {"decision": {"const": "FAIL"}, "model_execution_reachable": {"const": False}, "denial_reason": SYM}}],
)
defs["dispatch_preflight_receipt"] = top(
    "ppc5.dispatch_preflight_receipt.v5", "receipt_hash",
    {"dispatch_id": ID, "dispatch_ordinal": integer(), "dispatch_class": enum("MODEL_INFERENCE", "TOKENIZER_EXECUTION", "EMBEDDING_EXECUTION", "TRAINING", "CANARY", "CPU_BEHAVIORAL", "GPU_BEHAVIORAL", "GPU_JOB"), "executable_hash": H, "run_lock_hash": H, "pre_model_authority_hash": H, "immediate_state_receipt_hash": H, "mounted_artifact_refs": arr(aref("MOUNTED_ARTIFACT", ["BYTE_ARTIFACT_MANIFEST"])), "decision": enum("PERMIT", "DENY"), "denial_reason": NUL_SYM, "spawned_process_count": {"const": 0}},
    one_of=[{"properties": {"decision": {"const": "PERMIT"}, "denial_reason": {"type": "null"}}}, {"properties": {"decision": {"const": "DENY"}, "denial_reason": SYM}}],
)
defs["dispatch_result_receipt"] = top(
    "ppc5.dispatch_result_receipt.v5", "receipt_hash",
    {"preflight_receipt_hash": H, "process_started": {"type": "boolean"}, "process_id": {"oneOf": [integer(1), {"type": "null"}]}, "process_start_hash": NUL_H, "output_manifest_hash": NUL_H, "exit_code": {"oneOf": [{"type": "integer"}, {"type": "null"}]}},
    one_of=[
        {"properties": {"process_started": {"const": False}, "process_id": {"type": "null"}, "process_start_hash": {"type": "null"}, "output_manifest_hash": {"type": "null"}, "exit_code": {"type": "null"}}},
        {"properties": {"process_started": {"const": True}, "process_id": integer(1), "process_start_hash": H}},
    ],
)
defs["canary_receipt"] = top(
    "ppc5.canary_receipt.v5", "receipt_hash",
    {"run_lock_hash": H, "pre_model_authority_hash": H, "preflight_receipt_hash": H, "dispatch_result_hash": H, "expected_output_hash": H, "actual_output_hash": H, "decision": enum("PASS", "FAIL"), "first_failure": NUL_SYM},
    one_of=[
        {"properties": {"decision": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"decision": {"const": "FAIL"}, "first_failure": SYM}},
    ],
)
defs["runtime_integrity_receipt"] = top(
    "ppc5.runtime_integrity_receipt.v5", "receipt_hash",
    {"stage": {"const": "RUNTIME_VALIDITY"}, "predecessor_receipt_hash": H, "preflight_manifest_hash": H, "canary_receipt_hash": H, "perturbation_receipt_hashes": arr(H, minimum=1, unique=True), "runtime_evidence_manifest_hash": H, "decision": enum("PASS", "FAIL"), "model_execution_reachable": {"type": "boolean"}, "human_evidence": {"type": "null"}, "denial_reason": NUL_SYM},
    one_of=[{"properties": {"decision": {"const": "PASS"}, "model_execution_reachable": {"const": True}, "denial_reason": {"type": "null"}}}, {"properties": {"decision": {"const": "FAIL"}, "model_execution_reachable": {"const": False}, "denial_reason": SYM}}],
)
defs["t14_cold_replay_receipt"] = top(
    "ppc5.t14_cold_replay_receipt.v5", "receipt_hash",
    {"test_result_hash": H, "runtime_integrity_hash": H, "complete_life_manifest_hash": H, "reducer_output_manifest_hash": H, "candidate_decision_manifest_hash": H, "qualification_manifest_hash": H, "forbidden_claim_manifest_hash": H, "release_bytes_consumed": {"const": False}, "decision": enum("PASS", "FAIL"), "first_failure": NUL_SYM},
    one_of=[
        {"properties": {"decision": {"const": "PASS"}, "first_failure": {"type": "null"}}},
        {"properties": {"decision": {"const": "FAIL"}, "first_failure": SYM}},
    ],
)
defs["preclaim_authority_receipt"] = top(
    "ppc5.preclaim_authority_receipt.v5", "receipt_hash",
    {"stage": {"const": "PRE_SCIENTIFIC_CLAIM"}, "predecessor_receipt_hash": H, "runtime_integrity_hash": H, "t14_cold_replay_hash": H, "candidate_decision_refs": exact_refs(("D1A_DECISION", ["CLAIM_DECISION_RECEIPT"]), ("D1B_DECISION", ["CLAIM_DECISION_RECEIPT"]), ("D1C_DECISION", ["CLAIM_DECISION_RECEIPT"]), ("D1D_DECISION", ["CLAIM_DECISION_RECEIPT"]), ("INTERSECTION_DECISION", ["CLAIM_DECISION_RECEIPT"])), "dependency_manifest_hash": H, "endpoint_coverage_hash": H, "resource_manifest_hash": H, "decision": enum("PASS", "FAIL"), "model_execution_reachable": {"type": "boolean"}, "human_evidence": {"type": "null"}, "denial_reason": NUL_SYM},
    one_of=[{"properties": {"decision": {"const": "PASS"}, "model_execution_reachable": {"const": True}, "denial_reason": {"type": "null"}}}, {"properties": {"decision": {"const": "FAIL"}, "model_execution_reachable": {"const": False}, "denial_reason": SYM}}],
)


# Metadata used to generate a closed object inventory.
producer = {
    "BYTE_ARTIFACT_MANIFEST": "BYTE_MANIFEST_BUILDER",
    "GENERATOR_PARAMETER_SPACE": "BENCHMARK_CONSTRUCTION",
    "ENTROPY_SOURCE_CONTRACT": "BENCHMARK_CONSTRUCTION",
    "PRE_ENTROPY_MEMBERSHIP_MANIFEST": "RUN_DESIGN",
    "COMMON_SEED_BUNDLE": "SAMPLER",
    "GATE_REGISTRY": "RUN_DESIGN",
    "GENERATOR_MANIFEST": "BENCHMARK_CONSTRUCTION",
    "ENTROPY_RECEIPT": "SAMPLER",
    "LIFE_SAMPLE_RECEIPT": "SAMPLER",
    "SEMANTIC_TABLE": "BENCHMARK_CONSTRUCTION",
    "ASSAY_ASSIGNMENT": "ASSIGNMENT",
    "OVERLAP_MANIFEST": "BENCHMARK_CONSTRUCTION",
    "CONSTRUCTION_SCOPE_RECEIPT": "BENCHMARK_CONSTRUCTION",
    "PATH_SUITE_MANIFEST": "PATH_CONSTRUCTION",
    "PATH_PROOF": "PATH_CONSTRUCTION",
    "MODEL_VIEW": "STATE_RENDERER",
    "PRIVATE_CONTROLLER_RECEIPT": "CONTROLLER",
    "OPERATION_ENVELOPE": "MODEL_DISPATCH",
    "OPERATION_RESULT": "CONTROLLER_OR_TOOL",
    "QUEUE_SLOT_RECEIPT": "CONTROLLER",
    "QUEUE_EFFECT_RECEIPT": "CONTROLLER",
    "STATE_BODY": "TRANSITION_REDUCER",
    "TRANSITION_EVENT": "TRANSITION_REDUCER",
    "STATE_RECEIPT": "TRANSITION_REDUCER",
    "CONTROLLER_REGISTRY": "CONTRACT_AUTHOR",
    "PROVIDER_INGRESS": "CONTROLLER",
    "PROVIDER_RECEIPT": "READ_PROVIDER",
    "PROVIDER_AUDIT_RECEIPT": "READ_PROVIDER_AUDIT",
    "DESCRIPTIVE_PROVIDER_INGRESS": "DESCRIPTIVE_CONTROLLER",
    "DESCRIPTIVE_PROVIDER_RECEIPT": "DESCRIPTIVE_PROVIDER",
    "INTERVENTION_ROUTE_RECEIPT": "PRIVILEGED_ROUTER",
    "RESOLVED_RESPONSE_PROJECTION": "PRIVILEGED_ROUTER",
    "INTERVENTION_EMISSION_RECEIPT": "RESPONSE_INTERVENTION",
    "DREAM_INPUT": "DREAM_SCHEDULER",
    "DREAM_RENDER": "DREAM_RENDERER",
    "DREAM_RECEIPT": "DREAM",
    "CONTEXT_INSTALL_RECEIPT": "CONTEXT_POLICY",
    "ELIGIBILITY_RECEIPT": "EVIDENCE_GATE",
    "NOMINEE_UNIVERSE_RECEIPT": "EVIDENCE_GATE",
    "EVIDENCE_PROJECTION_RECEIPT": "ROOT_POLICY",
    "ROOT_SELECTION_RECEIPT": "ROOT_POLICY",
    "SLEEP_ROW": "WRITER",
    "CORPUS_MANIFEST": "WRITER",
    "TRAINER_EXECUTION_RECEIPT": "TRAINER",
    "ADAPTER_VALIDATION_RECEIPT": "VALIDATOR",
    "ADAPTER_MANIFEST": "VALIDATOR",
    "PUBLICATION_RECEIPT": "PUBLICATION",
    "STAGE_OUTCOME": "STATUS_REDUCER",
    "OBSERVATION": "OBSERVATION_REDUCER",
    "PAIRED_GATE_RESULT": "GATE_REDUCER",
    "ONE_SAMPLE_SAFETY_RESULT": "GATE_REDUCER",
    "MISSINGNESS_RESULT": "GATE_REDUCER",
    "GATE_POWER_RESULT": "POWER_REDUCER",
    "POWER_RECEIPT": "POWER_REDUCER",
    "RESOURCE_RECEIPT": "RESOURCE_REDUCER",
    "ASSAY_RESULT": "ASSAY_REDUCER",
    "HOLM_RESULT": "HOLM_REDUCER",
    "DEPENDENCY_MAP_RECEIPT": "CLAIM_REDUCER",
    "CLAIM_DECISION_RECEIPT": "CLAIM_REDUCER",
    "CLAIM_RELEASE_PACKAGE": "RELEASE_REDUCER",
    "IMPLEMENTATION_IDENTITY_RECEIPT": "BUILD_AUDIT",
    "IMPLEMENTATION_INDEPENDENCE_RECEIPT": "INDEPENDENCE_REDUCER",
    "FIXTURE_CASE": "TEST_CONSTRUCTION",
    "NEGATIVE_MUTATION": "TEST_CONSTRUCTION",
    "FIXTURE_UNIVERSE_MANIFEST": "TEST_CONSTRUCTION",
    "CASE_RESULT": "TEST_RUNNER",
    "MUTATION_RESULT": "TEST_RUNNER",
    "TEST_COVERAGE_RECEIPT": "TEST_REDUCER",
    "TEST_RESULT": "TEST_REDUCER",
    "ENDPOINT_COVERAGE_RECEIPT": "ENDPOINT_REDUCER",
    "POPULATED_RUN_LOCK": "RUN_DESIGN",
    "STATIC_SEAL_RECEIPT": "STATIC_SEALER",
    "SEALER_INDEPENDENCE_RECEIPT": "INDEPENDENCE_REDUCER",
    "INDEPENDENT_REVIEW_RECEIPT": "FRESH_REVIEWER",
    "ADVOCATE_RECEIPT": "AUTHOR_ADVOCATE",
    "ARCHITECTURE_RATIFICATION_RECEIPT": "HUMAN_INTAKE",
    "CONFORMANCE_RECEIPT": "CONFORMANCE_REDUCER",
    "HUMAN_RUN_RATIFICATION_RECEIPT": "HUMAN_INTAKE",
    "PRE_MODEL_AUTHORITY_RECEIPT": "AUTHORITY_REDUCER",
    "DISPATCH_PREFLIGHT_RECEIPT": "PREFLIGHT",
    "DISPATCH_RESULT_RECEIPT": "DISPATCH_AUDIT",
    "CANARY_RECEIPT": "CANARY",
    "RUNTIME_INTEGRITY_RECEIPT": "RUNTIME_REDUCER",
    "T14_COLD_REPLAY_RECEIPT": "COLD_REPLAY",
    "PRECLAIM_AUTHORITY_RECEIPT": "AUTHORITY_REDUCER",
}

top_level = [name.lower() for name in producer]
missing_defs = sorted(set(top_level) - set(defs))
if missing_defs:
    raise SystemExit(f"missing schema definitions: {missing_defs}")

schema = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "ppc5r5-contracts.schema.json",
    "title": "PPC5r5 closed contract union",
    "description": "Generated from drafts/build_r5_contract_schema.py; no generic semantic payload_ref envelopes.",
    "$defs": defs,
    "oneOf": [{"$ref": f"#/$defs/{name}"} for name in top_level],
}

hash_field_by_type = {}
for name in top_level:
    fields = defs[name]["properties"]
    candidates = [key for key in fields if key.endswith("_hash") and key not in {"predecessor_receipt_hash"}]
    own = [key for key in candidates if key in {"manifest_hash", "contract_hash", "bundle_hash", "receipt_hash", "table_hash", "assignment_hash", "proof_hash", "view_hash", "envelope_hash", "result_hash", "slot_hash", "effect_hash", "body_hash", "event_hash", "state_receipt_hash", "controller_hash", "registry_hash", "ingress_hash", "projection_hash", "input_hash", "render_hash", "observation_hash", "package_hash", "case_hash", "mutation_hash", "row_hash", "run_lock_hash"}]
    if not own:
        raise SystemExit(f"no self hash field for {name}")
    hash_field_by_type[name] = own[-1]

objects = []
for upper, stage in producer.items():
    name = upper.lower()
    objects.append({
        "type": name,
        "schema_ref": f"ppc5r5-contracts.schema.json#/$defs/{name}",
        "contract": defs[name]["properties"]["contract"]["const"],
        "domain": f"PPC5R5_{upper}",
        "producer": stage,
        "self_hash": hash_field_by_type[name],
        "payload_mode": "INLINE_CLOSED_FIELDS_NO_PAYLOAD_REF",
    })

inventory = {
    "schema_version": 5,
    "contract": "ppc5.object_inventory.v5",
    "closed_world": True,
    "canonical_json": "RFC8785-compatible project canonical JSON: sorted keys, compact separators, UTF-8, one LF; arrays retain contract order",
    "hash_algorithm": "SHA256(contract_utf8 || NUL || schema_version_ascii || NUL || canonical_object_without_self_hash)",
    "schema_bundle": "ppc5r5-contracts.schema.json",
    "unknown_type_policy": "REJECT",
    "objects": objects,
}


failure_order = [
    "INTEGRITY", "PREDISPATCH_BUDGET", "MISSING_CALL", "TOKEN_LIMIT",
    "PARSE_ERROR", "LOGICAL_ALLOWANCE", "SCHEDULE", "DOMAIN",
    "REFERENCE", "PREDICTION", "PROVIDER_MISSING", "ENVIRONMENT_INVALID",
    "SUCCESS",
]
zero_debit = {"calls": 0, "reads": 0, "actions": 0, "input_tokens": 0, "output_tokens": 0}


def controller_row(row_id, assay, program, phase, dispatch, required,
                   results, queue, success_next, error_next,
                   terminal=None, endpoint="NONE", **debit):
    row_debit = dict(zero_debit)
    row_debit.update(debit)
    return {
        "row_id": row_id,
        "assay_id": assay,
        "program": program,
        "phase_pattern": phase,
        "dispatch_kind": dispatch,
        "required_operation": required,
        "accepted_result_classes": results,
        "first_failure_order": failure_order,
        "debit": row_debit,
        "queue_effect": queue,
        "success_next_phase": success_next,
        "error_next_phase": error_next,
        "terminal_reason": terminal,
        "endpoint_effect": endpoint,
    }


rows = [
    controller_row("D1A_PROVIDER", "D1A", "DIRECT_PROVIDER", "PROVIDER[i<Q]", "PROVIDER", "NONE", ["FOUND", "NOT_FOUND", "PROVIDER_MISSING_NO_RETRY"], "NONE", "PROVIDER[i+1]", "PROVIDER[i+1]", endpoint="SELECTION_OBSERVATION"),
    controller_row("D1A_FINAL", "D1A", "DIRECT_PROVIDER", "PROVIDER[i=Q]", "CONTROLLER", "NONE", ["FINALIZE"], "NONE", "TERMINAL", "RUN_INVALID", terminal="PROVIDER_SEQUENCE_COMPLETE"),
    controller_row("D1B_AUTH_READ", "D1B", "D1B_AUTHENTIC", "READ[k<L]", "MODEL", "READ", ["READ_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "READ[k+1]", "READ[k]", calls=1, reads=1),
    controller_row("D1B_AUTH_PREDICT", "D1B", "D1B_AUTHENTIC", "PREDICT", "MODEL", "PREDICT", ["PREDICT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "ACT", "PREDICT", calls=1),
    controller_row("D1B_AUTH_ACT", "D1B", "D1B_AUTHENTIC", "ACT", "MODEL", "ACT", ["ACT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "TERMINAL", "ACT", terminal="SCHEDULE_COMPLETE", endpoint="ACTION_OBSERVATION", calls=1, actions=1),
    controller_row("D1B_ONE_PLAN", "D1B", "D1B_ONE_SHOT", "PLAN_READ[k<L]", "MODEL", "READ", ["SLOT_ACK", "ERROR", "MODEL_MISSING_NO_RETRY"], "QUEUE", "PLAN_READ[k+1]", "PLAN_READ[k+1]", calls=1, reads=1),
    controller_row("D1B_ONE_FLUSH", "D1B", "D1B_ONE_SHOT", "FLUSH[k<L]", "CONTROLLER", "NONE", ["READ_SUCCESS", "FLUSH_SKIPPED_REJECTED", "PROVIDER_MISSING_NO_RETRY"], "FLUSH", "FLUSH[k+1]", "FLUSH[k+1]"),
    controller_row("D1B_ONE_PREDICT", "D1B", "D1B_ONE_SHOT", "PREDICT", "MODEL", "PREDICT", ["PREDICT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "ACT", "FINALIZE_INCOMPLETE", calls=1),
    controller_row("D1B_ONE_ACT", "D1B", "D1B_ONE_SHOT", "ACT", "MODEL", "ACT", ["ACT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "TERMINAL", "FINALIZE_INCOMPLETE", terminal="SCHEDULE_COMPLETE", endpoint="ACTION_OBSERVATION", calls=1, actions=1),
    controller_row("D1B_ONE_FINAL", "D1B", "D1B_ONE_SHOT", "FINALIZE_INCOMPLETE", "CONTROLLER", "NONE", ["FINALIZE"], "DISCARD", "TERMINAL", "RUN_INVALID", terminal="SCHEDULE_INCOMPLETE", endpoint="ACTION_OBSERVATION"),
    controller_row("D1B_OPEN_PLAN", "D1B", "D1B_OPEN_LOOP", "PLAN_READ[k<L]", "MODEL", "READ", ["SLOT_ACK", "ERROR", "MODEL_MISSING_NO_RETRY"], "QUEUE", "PLAN_READ[k+1]", "PLAN_READ[k+1]", calls=1, reads=1),
    controller_row("D1B_OPEN_BLIND_PREDICT", "D1B", "D1B_OPEN_LOOP", "BLIND_PREDICT", "MODEL", "PREDICT", ["COMMIT_ACK", "ERROR", "MODEL_MISSING_NO_RETRY"], "QUEUE", "BLIND_ACT", "BLIND_ACT", calls=1),
    controller_row("D1B_OPEN_BLIND_ACT", "D1B", "D1B_OPEN_LOOP", "BLIND_ACT", "MODEL", "ACT", ["COMMIT_ACK", "ERROR", "MODEL_MISSING_NO_RETRY"], "QUEUE", "FLUSH[0]", "FLUSH[0]", calls=1, actions=1),
    controller_row("D1B_OPEN_FLUSH", "D1B", "D1B_OPEN_LOOP", "FLUSH[k<L]", "CONTROLLER", "NONE", ["READ_SUCCESS", "FLUSH_SKIPPED_REJECTED", "PROVIDER_MISSING_NO_RETRY"], "FLUSH", "FLUSH[k+1]", "FLUSH[k+1]"),
    controller_row("D1B_OPEN_COMMIT", "D1B", "D1B_OPEN_LOOP", "EXECUTE_COMMIT", "ENVIRONMENT", "NONE", ["ACT_SUCCESS", "COMMITMENT_ABSENT", "COMMITMENT_INVALID"], "EXECUTE_COMMIT", "TERMINAL", "TERMINAL", terminal="SCHEDULE_COMPLETE_OR_INCOMPLETE", endpoint="ACTION_OBSERVATION"),
    controller_row("D1C_READ", "D1C", "FIXED_BEHAVIOR", "READ[k<R]", "MODEL", "READ", ["READ_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "READ[k+1]", "READ[k+1]", calls=1, reads=1),
    controller_row("D1C_PREDICT", "D1C", "FIXED_BEHAVIOR", "PREDICT", "MODEL", "PREDICT", ["PREDICT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "ACT", "ACT", calls=1),
    controller_row("D1C_ACT", "D1C", "FIXED_BEHAVIOR", "ACT", "MODEL", "ACT", ["ACT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "TERMINAL", "TERMINAL", terminal="SCHEDULE_COMPLETE_OR_INCOMPLETE", endpoint="ACTION_OBSERVATION", calls=1, actions=1),
    controller_row("D1D_ROOT_TO_PROVIDER", "D1D", "D1D_TOTAL", "ROOT_SLEEP_PUBLICATION", "CONTROLLER", "NONE", ["PUBLISHED", "NO_ADAPTER", "TRAIN_FAILED", "DREAM_MISSING_NO_RETRY"], "NONE", "PROVIDER[0]", "PROVIDER[0]"),
    controller_row("D1D_PROVIDER", "D1D", "D1D_TOTAL", "PROVIDER[i<Q]", "PROVIDER", "NONE", ["FOUND", "NOT_FOUND", "PROVIDER_MISSING_NO_RETRY"], "NONE", "PROVIDER[i+1]", "PROVIDER[i+1]", endpoint="SELECTION_OBSERVATION"),
    controller_row("D1D_READ", "D1D", "D1D_TOTAL", "READ[k<R]", "MODEL", "READ", ["READ_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "READ[k+1]", "READ[k+1]", calls=1, reads=1),
    controller_row("D1D_PREDICT", "D1D", "D1D_TOTAL", "PREDICT", "MODEL", "PREDICT", ["PREDICT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "ACT", "ACT", calls=1),
    controller_row("D1D_ACT", "D1D", "D1D_TOTAL", "ACT", "MODEL", "ACT", ["ACT_SUCCESS", "ERROR", "MODEL_MISSING_NO_RETRY"], "NONE", "TERMINAL", "TERMINAL", terminal="SCHEDULE_COMPLETE_OR_INCOMPLETE", endpoint="ACTION_OBSERVATION", calls=1, actions=1),
]

controller_registry = {
    "contract": "ppc5.controller_registry.v5",
    "schema_version": 5,
    "operation_vocabulary": ["ACT", "PREDICT", "READ", "STOP"],
    "result_vocabulary": ["ACT_SUCCESS", "COMMITMENT_ABSENT", "COMMITMENT_INVALID", "COMMIT_ACK", "DREAM_MISSING_NO_RETRY", "ERROR", "ERROR_LIMIT", "FINALIZE", "FLUSH_SKIPPED_REJECTED", "FOUND", "MODEL_MISSING_NO_RETRY", "NO_ADAPTER", "NOT_FOUND", "PREDICT_SUCCESS", "PROVIDER_MISSING_NO_RETRY", "PUBLISHED", "READ_SUCCESS", "SLOT_ACK", "TRAIN_FAILED"],
    "terminal_vocabulary": ["BUDGET_EXHAUSTED", "ERROR_LIMIT", "MODEL_STOP", "NO_VALID_ACTION", "PROVIDER_SEQUENCE_COMPLETE", "RUN_INVALID", "SCHEDULE_COMPLETE", "SCHEDULE_COMPLETE_OR_INCOMPLETE", "SCHEDULE_INCOMPLETE"],
    "error_vocabulary": ["ACTION_LIMIT", "INVALID_ACTION", "INVALID_DOMAIN", "INVALID_REFERENCE", "MODEL_MISSING_NO_RETRY", "PARSE_ERROR", "PREDICTION_MISMATCH", "PREDICTION_REQUIRED", "READ_LIMIT", "RUN_INVALID", "SCHEDULE_VIOLATION", "TOKEN_LIMIT"],
    "first_failure_order": failure_order,
    "rows": rows,
}
controller_preimage = json.dumps(controller_registry, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
controller_registry["registry_hash"] = hashlib.sha256(b"ppc5.controller_registry.v5\x005\x00" + controller_preimage).hexdigest()

SCHEMA.write_text(json.dumps(schema, indent=2, ensure_ascii=False) + "\n")
INVENTORY.write_text(json.dumps(inventory, indent=2, ensure_ascii=False) + "\n")
CONTROLLER_REGISTRY.write_text(json.dumps(controller_registry, indent=2, ensure_ascii=False) + "\n")
print(f"wrote {SCHEMA} ({len(top_level)} top-level types)")
print(f"wrote {INVENTORY}")
print(f"wrote {CONTROLLER_REGISTRY}")
