"""Build the proposal-only extractable-SLEEP bootstrap V8 change.

This builder is intentionally model-free.  It binds the exact predecessor,
integration, scientific-core, and systems-core bytes; renders only an
architecture proposal; and rejects any drift in the 21 x 6 acceptance
lattice, registry/action-DAG closure, organism boundary, or authority scope.
It does not initialize intake, implement the proposal, or execute models,
tokenizers, data, adapters, checkpoints, CPUs, GPUs, science, claims, release,
or transfer.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
OUT = Path(__file__).with_name("change.json")
V5 = ROOT / "research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v5"
V6 = ROOT / "research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v6"
V7 = ROOT / "research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7"

INPUTS: tuple[tuple[str, str, str], ...] = (
    ("AGENTS.md", "1e3c413f3adbf172c409bc642bbf8242a736b0209461b6a7f81203450772f54e", "Binding research-agent operating contract."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v5/v6_scientific_core.json", "b45a62b02aa4be0f697a830e406d0c9ed48018e9a247324f261edb027e3f182c", "V6 scientific-core predecessor input."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v5/v6_capability_registry.json", "83223ebd602278689e0803170f124045e019e6c5654d02df63ed7e9e04353f0c", "V6 capability-registry predecessor input."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v5/v6_action_prerequisite_dag.json", "12d9120cb0ed537a600db72067dea9172febfd9c63aa5c2ece8a2e318b2ec49b", "V6 action-prerequisite-DAG predecessor input."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v6/v7_scientific_core.json", "f44f3512b1248d0a945b5e039459e068dbdc42ba97728026f572c3a572940710", "V7 scientific-core predecessor input."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v6/v7_capability_registry.json", "9c44fe870c56f3009b08512d48175c50a1378beeeebc378a7cfff2e89548c94d", "Defective V7 registry regenerated by the V8 systems core."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v6/v7_action_prerequisite_dag.json", "d176787d89784b54ed0fa65e47d0f08521835d49d4486c9e317e08ce64e3e6ca", "Defective V7 DAG regenerated by the V8 systems core."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/change.json", "d69ac7b3207b4eec18af552d968b7a396aa5b39a6bc6290072d14b3812e0cfc9", "Exact V7 proposal returned for rework."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/interpretation_science.json", "f428bceb89b8d1ed939b85b19c5488872de44618bb430ff9b6029132929b39a0", "Fresh V7 scientific interpretation."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/interpretation_systems.json", "98dba3149fd3e5e93888ce4f0db435b822b0ab22443a29f76c45c5b413b06d7b", "Fresh V7 systems interpretation."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/critique.json", "ee6f3f8f2d5abb19ba3e0f42ae32bdaee2a0e63c5a0c2c65d0415beca81e09ed", "V7 adversarial critique with fifteen concerns."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/consensus.json", "f4fbbf9544c8c74626226b7c5fc2fcfa93a7f843b99b68638562225110b94b51", "V7 adjudicated rework and fourteen disagreement dispositions."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/v8_blocker_resolution.md", "ba986cf1b4df614c76e7a21b138f2dd5c1e3b24e023fe59b7e2749cae511bd33", "Binding V8 proposal-only blocker resolution."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/v8_integration_requirements.json", "2f8d55096784e33a7a880ac1cf6252f29e613e0ad729ceb5d06499d10a899f6c", "Canonical V8 machine-checkable integration requirements."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/v8_scientific_core.json", "dc61df6c3947b3ef8a593d3b7ced928d8ceb5070454eb6c1271f0df9f258971d", "Independent V8 scientific core, reconciled to the integration contract."),
    ("research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v7/v8_systems_core.json", "cabeb07a18690c10a843f7eacb527d16ed6f5757fba69e78b76f9bf2a0a47c5e", "Independent V8 canonical systems source, registry/DAG, and visibility contract."),
)

REQUIREMENTS_PATH = V7 / "v8_integration_requirements.json"
SCIENCE_PATH = V7 / "v8_scientific_core.json"
SYSTEMS_PATH = V7 / "v8_systems_core.json"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(), object_pairs_hook=_reject_duplicate_keys)
    if not isinstance(value, dict):
        raise ValueError(f"expected JSON object: {path}")
    return value


def unique(values: Iterable[str], label: str) -> list[str]:
    items = list(values)
    if len(items) != len(set(items)):
        raise ValueError(f"duplicate {label}: {items}")
    return items


def ids(items: list[dict[str, Any]], key: str, label: str) -> list[str]:
    return unique((item[key] for item in items), label)


def assert_equal(actual: Any, expected: Any, label: str) -> None:
    if actual != expected:
        raise ValueError(f"{label} mismatch: expected={expected!r}, actual={actual!r}")


def verify_inputs() -> dict[str, dict[str, Any]]:
    loaded: dict[str, dict[str, Any]] = {}
    for relative, expected, _purpose in INPUTS:
        path = ROOT / relative
        if not path.is_file():
            raise FileNotFoundError(f"required proposal input absent: {relative}")
        actual = sha256(path)
        assert_equal(actual, expected, f"input hash for {relative}")
        if path.suffix == ".json":
            loaded[relative] = load_json(path)
    return loaded


def verify_declared_bindings(document: dict[str, Any], field: str) -> None:
    bindings = document[field]
    paths = unique((item["path"] for item in bindings), f"{field} path")
    for binding in bindings:
        path = ROOT / binding["path"]
        if not path.is_file():
            raise ValueError(f"declared source absent: {binding['path']}")
        assert_equal(sha256(path), binding["sha256"], f"declared hash {binding['path']}")
    if len(paths) != len(bindings):
        raise AssertionError("unreachable duplicate-binding check")


def expected_phase_rows(requirements: dict[str, Any]) -> list[dict[str, Any]]:
    contract = requirements["phase_row_contract"]
    rows: list[dict[str, Any]] = []
    for family_id in contract["family_ids_in_order"]:
        for phase in contract["phase_profiles_in_order"]:
            phase_id = phase["phase_id"]
            rows.append({
                "row_id": f"V8_ROW__{family_id}__{phase_id}",
                "receipt_id": f"R_{family_id}__{phase_id}__PASS",
                "family_id": family_id,
                "phase_id": phase_id,
                "producer_action_id": phase["producer_action_id"],
                "required_nonempty_root_fields": phase["required_nonempty_root_fields"],
                "exact_first_downstream_consumer_action_ids": phase[
                    "exact_first_downstream_consumer_action_ids"
                ],
            })
    return rows


def verify_phase_lattice(
    requirements: dict[str, Any], science: dict[str, Any], systems: dict[str, Any]
) -> list[dict[str, Any]]:
    cardinality = requirements["cardinality_contract"]
    contract = requirements["phase_row_contract"]
    expected = expected_phase_rows(requirements)
    assert_equal(len(contract["family_ids_in_order"]), 21, "family count")
    assert_equal(len(contract["phase_profiles_in_order"]), 6, "phase count")
    assert_equal(len(expected), 126, "derived phase-row count")
    assert_equal(cardinality["acceptance_family_count"], 21, "declared family count")
    assert_equal(cardinality["phase_count"], 6, "declared phase count")
    assert_equal(cardinality["phase_row_count"], 126, "declared row count")

    science_contract = science["acceptance_obligation_contract"]
    systems_contract = systems["acceptance_lattice"]
    family_ids = contract["family_ids_in_order"]
    assert_equal(
        [item["family_id"] for item in science_contract["families"]],
        family_ids,
        "scientific family order",
    )
    assert_equal(
        [item["test_id"] for item in systems_contract["families"]],
        family_ids,
        "systems family order",
    )
    assert_equal(science_contract["phase_profiles"], contract["phase_profiles_in_order"], "scientific phase profiles")
    system_phase_projection = [
        {
            key: phase[key]
            for key in (
                "phase_id", "producer_action_id",
                "required_nonempty_root_fields",
                "exact_first_downstream_consumer_action_ids",
            )
        }
        for phase in systems_contract["phase_specs"]
    ]
    assert_equal(system_phase_projection, contract["phase_profiles_in_order"], "systems phase profiles")

    science_rows = science_contract["phase_rows"]
    systems_rows = systems_contract["rows"]
    assert_equal(len(science_rows), 126, "scientific row count")
    assert_equal(len(systems_rows), 126, "systems row count")
    assert_equal(ids(science_rows, "row_id", "scientific row ID"), [row["row_id"] for row in expected], "scientific row IDs")
    assert_equal(ids(systems_rows, "row_id", "systems row ID"), [row["row_id"] for row in expected], "systems row IDs")
    assert_equal(ids(science_rows, "receipt_id", "scientific receipt ID"), [row["receipt_id"] for row in expected], "scientific receipt IDs")
    assert_equal(ids(systems_rows, "receipt_id", "systems receipt ID"), [row["receipt_id"] for row in expected], "systems receipt IDs")

    for target, scientific, system in zip(expected, science_rows, systems_rows):
        for key in (
            "row_id", "receipt_id", "family_id", "phase_id",
            "producer_action_id", "exact_first_downstream_consumer_action_ids",
        ):
            assert_equal(scientific[key], target[key], f"science {target['row_id']} {key}")
            assert_equal(system[key], target[key], f"systems {target['row_id']} {key}")
        assert_equal(
            scientific["required_nonempty_root_fields"],
            target["required_nonempty_root_fields"],
            f"science {target['row_id']} required roots",
        )
        for required in target["required_nonempty_root_fields"]:
            slot_key = required[:-1] + "_slots" if required.endswith("s") else required + "_slots"
            slots = system.get(slot_key)
            if required == "review_root":
                slots = [system.get("review_root_requirement")]
            if not slots or slots == ["NOT_APPLICABLE"]:
                raise ValueError(f"systems row lacks required {required}: {target['row_id']}")
        if system["prospective_state"] != "UNPRODUCED_UNEVALUATED":
            raise ValueError(f"nonprospective systems row: {target['row_id']}")

    manifests = systems_contract["phase_manifests"]
    assert_equal(len(manifests), 6, "phase-manifest count")
    for phase, manifest in zip(contract["phase_profiles_in_order"], manifests):
        phase_id = phase["phase_id"]
        phase_rows = [row for row in expected if row["phase_id"] == phase_id]
        assert_equal(manifest["manifest_id"], f"V8_PHASE_MANIFEST__{phase_id}", f"{phase_id} manifest ID")
        assert_equal(manifest["expected_row_ids"], [row["row_id"] for row in phase_rows], f"{phase_id} manifest rows")
        assert_equal(manifest["expected_receipt_ids"], [row["receipt_id"] for row in phase_rows], f"{phase_id} manifest receipts")
        assert_equal(manifest["row_count"], 21, f"{phase_id} manifest row count")
        assert_equal(manifest["producer_action_ids"], [phase["producer_action_id"]], f"{phase_id} manifest producer")
        assert_equal(manifest["first_consumer_action_ids"], phase["exact_first_downstream_consumer_action_ids"], f"{phase_id} manifest consumers")
        if manifest["prospective_state"] != "UNPRODUCED_UNEVALUATED":
            raise ValueError(f"nonprospective phase manifest: {phase_id}")
    return expected


def verify_registry_and_dag(requirements: dict[str, Any], systems: dict[str, Any]) -> None:
    registry = systems["canonical_registry_source"]
    dag = systems["finite_action_dag"]
    required = requirements["required_v8_object_identities"]

    lifetimes = set(ids(registry["lifetime_classes"], "lifetime_id", "lifetime ID"))
    sources = set(ids(registry["registered_sources"], "source_id", "source ID"))
    principals = set(unique(registry["registered_principals"], "principal ID"))
    operations = set(ids(registry["operations"], "operation", "operation ID"))
    artifacts_list = registry["artifact_definitions"]
    artifacts = {item["artifact_class"]: item for item in artifacts_list}
    if len(artifacts) != len(artifacts_list):
        raise ValueError("duplicate artifact class")
    schema_defs = set(ids(registry["schema_definitions"], "schema_id", "schema ID"))
    actions_list = dag["control_actions"]
    actions = {item["action_id"]: item for item in actions_list}
    if len(actions) != len(actions_list):
        raise ValueError("duplicate action ID")

    if not set(required["lifetime_ids_that_must_resolve"]) <= lifetimes:
        raise ValueError("required immutable lifetime is unresolved")
    if not set(required["artifact_class_ids"]) <= set(artifacts):
        raise ValueError("required artifact class is unresolved")
    if not set(required["operation_ids"]) <= operations:
        raise ValueError("required operation is unresolved")
    if not set(required["schema_ids"]) <= schema_defs:
        raise ValueError("required exact schema is unresolved")
    if not set(required["principal_ids"]) <= principals | sources:
        raise ValueError("required principal/source is unresolved")

    required_actions: set[str] = set()
    for field in (
        "phase_producer_action_ids", "phase_boundary_action_ids",
        "candidate_and_reporting_action_ids", "release_chain_action_ids_in_order",
    ):
        required_actions.update(required[field])
    if not required_actions <= set(actions):
        raise ValueError(f"required action IDs unresolved: {sorted(required_actions - set(actions))}")
    assert_equal(
        systems["release_chain"]["ordered_actions"],
        required["release_chain_action_ids_in_order"],
        "release action order",
    )

    known_producers = principals | sources
    for item in artifacts_list:
        if item["lifetime_id"] not in lifetimes:
            raise ValueError(f"unresolved lifetime on {item['artifact_class']}")
        if item["sole_producer_id"] not in known_producers:
            raise ValueError(f"unresolved producer on {item['artifact_class']}")
        if not item["payload_schema_id"]:
            raise ValueError(f"missing payload schema on {item['artifact_class']}")

    source_projection: dict[str, list[str]] = {source: [] for source in sources}
    for item in artifacts_list:
        if item["sole_producer_id"] in sources:
            source_projection[item["sole_producer_id"]].append(item["artifact_class"])
    declared_projection = {
        item["source_id"]: item["produced_artifact_classes"]
        for item in registry["materialized_source_product_manifests"]
    }
    assert_equal(set(declared_projection), sources, "source-product manifest source set")
    for source in sources:
        assert_equal(sorted(declared_projection[source]), sorted(source_projection[source]), f"source-product projection {source}")

    phase_manifest_ids = {
        item["manifest_id"] for item in systems["acceptance_lattice"]["phase_manifests"]
    }
    producer_for: dict[str, dict[str, Any]] = {}
    for action in actions_list:
        if action["principal_id"] not in principals | sources:
            raise ValueError(f"unregistered action principal/source: {action['action_id']}")
        for product in action["produces_receipt_ids"]:
            # A class can be emitted by distinct phase-specific instances.  The
            # sealed instance manifest supplies the unique concrete identity.
            producer_for.setdefault(product, action)
        for prerequisite in action["prerequisite_receipt_ids"]:
            if prerequisite not in artifacts and prerequisite not in phase_manifest_ids:
                raise ValueError(f"unresolved prerequisite {prerequisite} on {action['action_id']}")
    for action in actions_list:
        for prerequisite in action["prerequisite_receipt_ids"]:
            producer = producer_for.get(prerequisite)
            if producer and producer["topological_rank"] >= action["topological_rank"]:
                raise ValueError(f"noncausal prerequisite {prerequisite} on {action['action_id']}")

    if systems["candidate_closure"]["operation"] != "SEAL_CANDIDATE_CLOSURE_ATOMIC":
        raise ValueError("candidate closure is not atomic")
    if systems["promotion_cas"]["operation"] != "PROMOTE_CAS_ATOMIC":
        raise ValueError("promotion operation is not atomic CAS")
    if systems["release_chain"]["transfer_operation"] != "TRANSFER_OPAQUE":
        raise ValueError("release is not opaque transfer")
    if systems["finite_action_dag"]["first_consumer_map"] != {
        item["phase_id"]: item["exact_first_downstream_consumer_action_ids"]
        for item in requirements["phase_row_contract"]["phase_profiles_in_order"]
    }:
        raise ValueError("DAG first-consumer map differs from integration contract")


def context_files() -> list[dict[str, str]]:
    return [
        {"path": path, "sha256": expected, "purpose": purpose}
        for path, expected, purpose in INPUTS
    ]


def node(node_id: str, before: str, after: str, rationale: str, operation: str = "modify") -> dict[str, str]:
    return {"operation": operation, "node_id": node_id, "before": before, "after": after, "rationale": rationale}


def edge(edge_id: str, source: str, target: str, before: str, after: str, rationale: str, operation: str = "modify") -> dict[str, str]:
    return {"operation": operation, "edge_id": edge_id, "from": source, "to": target, "before": before, "after": after, "rationale": rationale}


def build_graph(systems: dict[str, Any]) -> dict[str, list[dict[str, str]]]:
    core_root = sha256(SYSTEMS_PATH)
    nodes = [
        node("THINK", "V7 described THINK indirectly through waking-child infrastructure.", "The continuing child's waking thought, action, public outcome, judgment, and prospective-intention stream.", "Make the first and only continuing cognitive function explicit.", "add"),
        node("DREAM", "V7 treated DREAM as disposable waking context.", "Disposable management of finite waking context only; it is neither evidence, persistent memory authority, nor a SLEEP or candidate input.", "Preserve the second cognitive function without widening it."),
        node("SLEEP", "V7 specified a resolver, fresh constructor, stager, evaluator, and promotion path with unresolved structural closure.", "Noncreative compilation of independently eligible, grounded, same-life child-authored experience followed by a fresh-from-immutable-birth personal LoRA write; candidate closure and activation are laboratory enforcement, not extra cognition.", "Preserve the third cognitive function and close its information boundary."),
        node("ORGANISM_FUNCTION_SET", "The function set was stated in prose.", "The cognitive-function set is exactly [THINK,DREAM,SLEEP], cardinality three; every other V8 component is laboratory infrastructure.", "Prevent registry, gate, receipt, audit, evaluator, bootstrap, parent, or release machinery from becoming a fourth organ.", "add"),
        node("PRIMARY_CAUSAL_DESIGN", "V7 labels could overidentify a teachability mechanism.", "Primary design is exactly birth {D,T} by parent {absent,fixed}; M0 is a separate entry-damage/headroom diagnostic; adaptive parenting is a separately randomized extension. Formal estimands are exactly Delta_R, Delta_F, and Delta_E at ages 0,8,16,24,32.", "Identify only complete randomized-regime contrasts under the V8 scientific core.", "add"),
        node("DEFERRED_SCIENCE_CONTRACTS", "V7 named future contracts but left several first-use edges ambient.", "Bootstrap rendering/control, model-free support, cumulative coverage/dose/capacity, matched opportunity, statistics/stopping/safety, and held-out native-use remain separately ratified immutable roots and typed prerequisites before first affected use; every value remains DEFERRED_TO_SEPARATELY_RATIFIED_BOOTSTRAP_CONTRACT where applicable.", "Do not choose or execute model, tokenizer, corpus, example, habit, mask, optimizer, adapter, capacity, statistic, or resource bytes in this proposal.", "add"),
        node("ACCEPTANCE_PHASE_LATTICE", "V7 aliased each family's six phases behind shared receipt identities and a false global implementation boundary.", "Exactly 126 unique family-by-phase rows and receipts are generated in canonical family-major order; six manifests each bind exactly 21 rows and their exact first downstream consumers.", "Make every phase constructible and fail closed without shared-pass aliases.", "add"),
        node("CANONICAL_REGISTRY_AND_DAG", "V7 registry/DAG had missing producers, schemas, lifetimes, actions, and stale names.", f"Systems core {core_root} is the sole canonical source for deterministic registry, capability, bridge, finite action-DAG, receipt, result, and schema views; generated views cannot be hand-patched.", "Resolve every reference and producer exactly once while rejecting unknown or stale objects.", "add"),
        node("ACTION_INSTANCE_MANIFEST", "V7 umbrella actions hid repeated protected invocations.", "Before any protected effect, one immutable finite manifest enumerates each root, arm, life, age, epoch, principal, invocation, retry, input root, result identity, authority, matched opportunity, contract, predecessor, expiry/replay rule, and guarded row.", "No loop, wildcard, callback, range, or dispatcher may hide a token, call, write, allocation, audit, claim, or transfer.", "add"),
        node("CANDIDATE_CLOSURE_STORE", "V7 could expose staging authority before candidate and construction trace were atomically closed.", "SEAL_CANDIDATE_CLOSURE_ATOMIC equality-binds terminal candidate, complete trace, immutable birth, zero initializer, cumulative evidence, writer/support/coverage-dose contracts, seed, terminal success, non-dereferenceable descriptor, and narrow lineage fact in one transaction.", "Candidate-only, trace-only, partial, failed, or crashed construction yields no descriptor or staging authority.", "add"),
        node("PROMOTION_CAS_STORE", "V7 named atomic promotion without a complete wire/idempotency state machine.", "PROMOTE_CAS_ATOMIC binds the complete prior head/life, staged candidate, preservation verdict, replacements, namespace, nonce, key, request digest, committed response, and receipt at one linearization point; every noncommit preserves prior head and life.", "Make concurrent, stale, crash, lost-response, retry, replay, and substitution histories constructible and deterministic.", "add"),
        node("SPLIT_EXECUTOR_SCORER_REPORTER", "V7 did not gate the analysis packet before all reporting paths.", "Executor, scorer, and reporter are separate principals and action instances. Reporter consumes frozen score roots and FROZEN_SCIENTIFIC_ANALYSIS_PACKET before CPU/GPU reporting; neither reports nor scores feed development, SLEEP, audit authority, or release.", "Keep measurement one-way and labels prospective.", "add"),
        node("G0_ECHO_CLOSED_GATE", "V7 reused coarse G0 authority without exact root echoes.", "One exact G0 harness plus action-specific authority binds registry, DAG, parser, issuer, bridge, validator, gate, fake artifacts/dispatchers, faults, paths, forbidden scope, expected outputs, action IDs, nonce, and expiry; every child result and installed gate echo all roots.", "Prevent mixed, stale, substituted, or more-permissive G0 bytes.", "add"),
        node("WHOLE_SYSTEM_VISIBILITY", "V7 covered only capability IDs and did not close value/count/order/timing/cache/retry/error channels.", "The systems-core universe spans every registry/DAG object and all seven observable channels. This proposal materializes the exact category-channel policy projection; before any future sealed invocation, an object-level WHOLE_SYSTEM_VISIBILITY_MANIFEST is regenerated from exact registry/sub-DAG roots.", "No category, omitted object, hash, root, nonce, ordering, timing, cache, retry, or error behavior can become an ambient or covert path.", "add"),
        node("PRODUCER_CLOSED_RELEASE_CHAIN", "V7's release action could bypass real manifest, audit, wrapper, and authority producers.", "Eight ordered actions seal real dependency and dispatcher manifests, run blindness and lineage audits, register the concrete class/root wrapper, verify external authority, bind the nine-field tuple, and perform exactly one opaque transfer.", "Only deterministic narrow attestations reach authority; detailed findings remain quarantined.", "add"),
    ]
    edges = [
        edge("PARENTING_ROUTE_TO_THINK", "LABORATORY_PARENTING_INFRASTRUCTURE", "THINK", "V7 could leave parent causality semantically underspecified.", "parent_or_repetition -> waking_child_context -> child_thought -> child_action -> public_outcome -> complete_committed_child_trace -> independent_same_life_eligibility -> later_SLEEP; the only direct infrastructure-to-organism contact is waking context.", "Preserve parenting as waking influence without a teacher-to-gradient shortcut."),
        edge("THINK_TO_SLEEP_ELIGIBILITY", "THINK", "SLEEP", "V7 support resolution was not fully producer-closed.", "Only a later complete child-authored commit plus matching same-life public action/outcome under the frozen model-free support contract may cross this edge.", "Parent assertion, copied wording, repetition state, DREAM state, favorable outcome, and compiler inference cannot backfill child authorship."),
        edge("DREAM_TO_THINK_CONTEXT_ONLY", "DREAM", "THINK", "DREAM already managed disposable waking context.", "DREAM may supply disposable waking context only; none of its bytes, semantics, identifiers, roots, counts, order, timing, cache, retry, or errors reaches evidence, SLEEP, dose, candidates, or gradients.", "Preserve context management while closing derived side channels."),
        edge("PHASE_ROWS_TO_EXACT_CONSUMERS", "ACCEPTANCE_PHASE_LATTICE", "CANONICAL_REGISTRY_AND_DAG", "V7 phase passes were shared aliases.", "Every unique row receipt is equality-bound into its 21-child phase manifest, and each exact first consumer directly requires that manifest before invocation.", "Make missing, duplicate, extra, wrong-phase/root/producer/reviewer/consumer, stale, expired, or replayed rows deny.", "add"),
        edge("REGISTRY_DAG_TO_ACTION_INSTANCES", "CANONICAL_REGISTRY_AND_DAG", "ACTION_INSTANCE_MANIFEST", "V7 generic actions did not enumerate finite calls.", "The sealed manifest expands every protected action into finite producer-closed instances with exact prerequisite roots and strictly increasing topological ranks.", "No action produces its own gate or hides a protected nested call.", "add"),
        edge("SLEEP_TO_ATOMIC_CANDIDATE_CLOSURE", "SLEEP", "CANDIDATE_CLOSURE_STORE", "V7 used separate candidate and trace writes before descriptor issuance.", "Fresh-from-birth construction closes candidate and complete trace atomically before any descriptor, equality-only head token, stage, preservation evaluation, or promotion.", "Prior active head and postconstruction decisions cannot condition candidate bytes.", "add"),
        edge("CANDIDATE_CLOSURE_TO_ATOMIC_PROMOTION", "CANDIDATE_CLOSURE_STORE", "PROMOTION_CAS_STORE", "V7's postclosure and CAS order was not structurally complete.", "A non-dereferenceable descriptor permits staging; a candidate-root-bound preservation verdict then feeds the one store-mediated PROMOTE_CAS_ATOMIC transaction.", "All faults either commit once or preserve the exact prior continuing life.", "add"),
        edge("MATCHED_OPPORTUNITY_TO_EVERY_INSTANCE", "DEFERRED_SCIENCE_CONTRACTS", "ACTION_INSTANCE_MANIFEST", "V7 matched opportunity was coarse.", "Every experimental instance consumes its own immutable receipt binding arms, root/life/age/epoch/action, exposure/order, parent or substitute opportunity, tools/actions, tokens, wall time, retries, calls, CPU/GPU allocation, and initialized write opportunity.", "Fixed parenting remains byte/timing/opportunity invariant across child histories and neither parent has a personal adapter.", "add"),
        edge("TYPED_EVIDENCE_TO_GPU_AND_CLAIM", "DEFERRED_SCIENCE_CONTRACTS", "SPLIT_EXECUTOR_SCORER_REPORTER", "V7 left pre-GPU, reporter, and claim evidence in prose.", "Concrete uniquely produced receipts gate GPU dispatch; the reporter consumes the exact analysis packet before reporting; the claim-row producer validates but cannot create POWERED_CLAIM_EVIDENCE_MANIFEST.", "Authority and generic phase completion never substitute for scientific evidence.", "add"),
        edge("SYSTEMS_CORE_TO_WHOLE_VISIBILITY", "CANONICAL_REGISTRY_AND_DAG", "WHOLE_SYSTEM_VISIBILITY", "V7 generated only a principal-by-capability matrix.", "Generate the universe from every principal, source, lifetime, artifact/payload, schema, operation request/result, capability, bridge, action/instance, receipt, manifest, result, terminal output, error, and observable channel in the systems core.", "Every absent object-specific edge is forbidden.", "add"),
        edge("G0_TO_INSTALLED_GATE", "G0_ECHO_CLOSED_GATE", "CANONICAL_REGISTRY_AND_DAG", "V7 did not echo all trust roots through each child result.", "The installed gate exists only after both preimplementation phase manifests and every exact echo-closed G0 child result match the one harness manifest and action-specific authority.", "G0 remains fake-only and grants no implementation or execution authority.", "add"),
        edge("NARROW_AUDITS_TO_OPAQUE_RELEASE", "WHOLE_SYSTEM_VISIBILITY", "PRODUCER_CLOSED_RELEASE_CHAIN", "V7 fixed-size attestations did not close behavioral covert channels or the producer chain.", "Canonical finite attestations use verifier nonce/deadline, deterministic padding/order/count/timing/cache/retry/error behavior, and only PASS/FAIL plus a paired reason; exact external authority and class/root tuple equality then gate one opaque transfer.", "Quarantined findings cannot affect any permitted verifier-visible bit or timing behavior.", "add"),
    ]
    return {"nodes": nodes, "edges": edges}


def loop(loop_id: str, before: str, after: str, trigger: str, reads: list[str], writes: list[str], stop: str, rationale: str) -> dict[str, Any]:
    return {
        "operation": "modify", "loop_id": loop_id, "before": before, "after": after,
        "trigger": trigger, "reads": reads, "writes": writes,
        "stop_condition": stop, "rationale": rationale,
    }


def build_loops() -> dict[str, list[dict[str, Any]]]:
    return {"loops": [
        loop("SLEEP_COMPILE_WRITE_COMMIT", "V7 did not atomically close candidate and complete trace before staging.", "SLEEP resolves only same-life grounded child-authored evidence, reconstructs from immutable birth and zero delta over the complete cumulative eligible corpus, atomically closes candidate plus trace, then permits staging, preservation evaluation, and one atomic promotion.", "Only after the frozen cutoff and exact support, writer, coverage/dose/capacity, matched-opportunity, action-instance, and applicable phase prerequisites exist.", ["CHILD_GROUNDED_TRACE", "PUBLIC_OBSERVATION", "FROZEN_SUPPORT_RESOLVER_CONTRACT", "FROZEN_CUMULATIVE_COVERAGE_DOSE_CONTRACT", "FROZEN_SLEEP_WRITER_CONTRACT", "IMMUTABLE_BIRTH_ARTIFACT", "ZERO_EFFECTIVE_DELTA_INITIALIZER", "MATCHED_SOLO_RESOURCE_OPPORTUNITY_RECEIPT", "ACTION_INSTANCE_MANIFEST"], ["ELIGIBLE_CHILD_LIFE_EVIDENCE", "CANDIDATE_CONSTRUCTION_TRACE", "CANDIDATE_CLOSURE_MANIFEST", "SEALED_CANDIDATE_DESCRIPTOR"], "Missing/undecidable support, any parent/repetition/DREAM/prior-head/science/audit taint, incomplete cumulative coverage, nonzero initializer, capacity overflow, or closure fault stops before write/stage and preserves life.", "SLEEP remains noncreative and fresh from birth."),
        loop("CANDIDATE_PRESERVATION_AND_PROMOTION", "V7 lacked exact atomic closure and durable CAS retry semantics.", "A stager receives only the closure-derived non-dereferenceable descriptor and equality-only complete-head token; a fresh evaluator emits a candidate-root-bound verdict; the lineage store executes exactly one PROMOTE_CAS_ATOMIC or no mutation.", "After SEAL_CANDIDATE_CLOSURE_ATOMIC succeeds and all action-instance prerequisites match.", ["CANDIDATE_CLOSURE_MANIFEST", "SEALED_CANDIDATE_DESCRIPTOR", "COMMITTED_TRANSACTION_CAS_TOKEN", "FROZEN_PRESERVATION_PANEL", "TRANSACTION_CACHE_RETRY_CONTRACT"], ["STAGED_CANDIDATE_DESCRIPTOR", "PRESERVATION_EVIDENCE", "PROMOTION_VERDICT", "PROMOTION_TRANSACTION_RECEIPT", "ACTIVE_WEIGHT_ARTIFACT"], "Partial closure, rejection, stale head, changed candidate/verdict, conflicting key, replay, expiry, or crash before linearization preserves exact prior head/life; identical postcommit retry returns identical response without mutation.", "Activation cannot retroactively condition SLEEP construction."),
        loop("BOOTSTRAP_BUILD_AND_BIRTH", "V7 left exact render/control bytes deferred but some evidence edges ambient.", "Construct matched D and T births only under a separately ratified target-blind rendering/control contract; M0 remains a separate diagnostic. No bootstrap example count, habit count, corpus content, tokenizer, masks, weights, optimizer, rank, dose, or data is selected here.", "Only after exact future contract roots, target-blindness/semantic-control receipts, action authority, and matched opportunity exist.", ["FROZEN_M0", "STATIC_BOOTSTRAP_SPEC", "FROZEN_BOOTSTRAP_RENDERING_CONTROL_CONTRACT", "BOOTSTRAP_WRITER_MATERIALIZATION_CONTRACT", "FROZEN_STATISTICS_STOPPING_SAFETY_CONTRACT"], ["PAIRED_BOOTSTRAP_CORPUS", "IMMUTABLE_BIRTH_ARTIFACT", "BOOTSTRAP_SEMANTIC_CONTROL_AUDIT_RECEIPT", "BOOTSTRAP_TARGET_BLINDNESS_AUDIT_RECEIPT"], "Target vocabulary, answer, hidden rule, proxy, policy-isomorphic template, unmatched opportunity, entry damage/ceiling/headroom failure, or missing contract denies first use.", "The intervention is a birth condition, not a fourth organ or result."),
        loop("PARENT_REPETITION_AND_FADE", "V7 did not enumerate every parent invocation and opportunity.", "At ages 1,9,17,25, fixed-parent bytes/timing/opportunity are history-invariant and matched to nonparent substitutes; adaptive parenting is separately randomized under a frozen policy. Repetition is waking practice of meaning across varied situations.", "A sealed finite action instance and exact parent/opportunity contract authorize one waking invocation.", ["FIXED_LESSON_TABLE", "FIXED_SCHEDULE_CURSOR", "FIXED_PARENT_EXOGENEITY_CONTRACT", "ADAPTIVE_PARENT_POLICY_CONTRACT", "MATCHED_SOLO_RESOURCE_OPPORTUNITY_RECEIPT", "REPETITION_ENACTMENT_CONTRACT"], ["FIXED_LIVE_PARENT_MESSAGE", "ADAPTIVE_LIVE_PARENT_MESSAGE", "FIXED_PARENT_AUDIT_EVENT", "ADAPTIVE_PARENT_AUDIT_EVENT", "CHILD_GROUNDED_TRACE", "PUBLIC_OBSERVATION"], "History-dependent fixed bytes/timing/opportunity, stale cursor, copied-string uptake, personal parent adapter, or any direct/derived parent/repetition route to SLEEP stops before emission or eligibility.", "Parenting acts through the child's later waking thought/action/grounding only."),
        loop("DREAM_DISPOSABLE_CONTEXT_MANAGEMENT", "V7 stated DREAM disposal without a whole-channel visibility closure.", "DREAM manages finite waking context and may affect later waking THINK only; all DREAM value/count/order/timing/cache/retry/error observables are forbidden from evidence, compilation, dose, candidates, gradients, audits, authority, and release.", "A finite waking-context boundary requests disposable context management.", ["CHILD_GROUNDED_TRACE"], ["DREAM_CACHE"], "Any persistent, loss-bearing, evidence-bearing, cross-life, or covert DREAM output beyond waking context is denied and destroyed.", "Preserve DREAM as the second and only disposable cognitive function."),
        loop("DISPOSABLE_SCIENTIFIC_EVALUATION", "V7 did not packet-gate every reporter before invocation.", "Separate executor, model-free scorer, and reporter instances close transcript before truth scoring and bind scores to the frozen analysis packet before CPU/GPU reporting; no artifact returns to development or release authority.", "Only at prospectively frozen ages after exact assignment, task, matched opportunity, statistics, phase, review, and action authority prerequisites.", ["ACTIVE_WEIGHT_ARTIFACT", "PUBLIC_OBSERVATION", "HIDDEN_EVALUATION_TRUTH", "FROZEN_SCIENTIFIC_ANALYSIS_PACKET", "MATCHED_SOLO_RESOURCE_OPPORTUNITY_RECEIPT", "ACTION_INSTANCE_MANIFEST"], ["EXAM_TRANSCRIPT", "SCIENTIFIC_SCORE_RECORD", "GPU_SCORE_RECORDS", "SCIENTIFIC_REPORT", "REPORT_BINDING_RECEIPT"], "Executor truth/score access, scorer model access, ambient analysis/labels, packet-after-report order, pseudoreplication, or feedback fails closed.", "Evaluation measures rather than teaches."),
        loop("PHASE_GATED_ACTION_LATTICE", "V7 used 21 shared coarse acceptance objects.", "For each of 21 families, exactly six prospective rows are independently produced only when their phase evidence is constructible; six manifests equality-bind the 21 child roots and gate only the exact first consumers.", "A separately authorized phase producer receives every exact subject/input/fixture/implementation/result/review root required for its phase.", ["G0_EXACT_HARNESS_MANIFEST", "IMPLEMENTATION_MANIFEST", "CPU_DOMAIN_RESULT_MANIFEST", "GPU_SCIENCE_RESULT_MANIFEST", "POWERED_CLAIM_EVIDENCE_MANIFEST", "INDEPENDENT_REVIEW_RECEIPT"], ["ACCEPTANCE_TEST_PHASE_ROW_RECEIPT", "ACCEPTANCE_TEST_PHASE_MANIFEST"], "Missing, duplicate, extra, aliased, stale, failed, wrong-phase/root/producer/reviewer/consumer, expired, replayed, or self-produced gates deny the exact consumer.", "Phase-correct evidence replaces V7's global before-implementation fiction."),
        loop("AUDIT_EXTERNAL_AUTHORITY_AND_RELEASE", "V7 release could bypass real producer actions and leak detailed findings behaviorally.", "Seal real dependency/dispatcher manifests; run blindness and lineage audits; expose only canonical narrow attestations; register the concrete class/root wrapper; verify exact external authority; equality-bind nine tuple fields; execute one content-independent opaque transfer.", "Only after applicable G4 manifest, powered evidence where relevant, separate exact release authority, and all earlier release-chain receipts exist.", ["DECLARED_DEPENDENCY_MANIFEST", "DISPATCHER_MANIFEST", "BLINDNESS_AUDIT_ATTESTATION", "LINEAGE_AUDIT_ATTESTATION", "EXTERNAL_HUMAN_AUTHORIZATION", "RELEASE_TARGET_ARTIFACT", "RELEASE_TUPLE_BINDING", "AUTHORITY_VERDICT", "RELEASE_TUPLE_EQUALITY_RECEIPT"], ["RELEASE_RECEIPT"], "Any bypass, detailed-finding influence, stale/substituted/expired/replayed input, class/root/tuple mismatch, inspection, widening, or second transfer returns canonical denial.", "Audit and authority remain laboratory governance, never cognition or scientific evidence."),
    ]}


def claim(operation: str, claim_id: str, before: str, after: str, evidence_needed: str, headline_eligible: bool) -> dict[str, Any]:
    return {"operation": operation, "claim_id": claim_id, "before": before, "after": after, "evidence_needed": evidence_needed, "headline_eligible": headline_eligible}


def build_claims() -> dict[str, list[dict[str, Any]]]:
    return {"claims": [
        claim("retire", "C_V1_NATIVE_WRITER_CERTIFIED", "R2 and an earlier write swarm were treated as certification.", "Old-writer and dose-confounded observations receive no V8 successor credit.", "No successor evidence can revive this retired claim.", False),
        claim("add", "C_EXPERIENCE_EXTRACTABLE_AND_USABLE", "Source fit or recitation could be mistaken for usable extraction.", "Only conditional on later powered independent-root evidence may fresh-from-birth personal SLEEP be described as supporting held-out cue extraction and native action on fresh homologous tasks without textual retrieval, compiler-created cognition, or interface harm.", "Exact held-out/native-use, contamination, no-retrieval, adapter-off, deranged, wrong-life, replay/filler, provenance, preservation, interface, uncertainty, multiplicity, missingness, safety, and G4 authority receipts.", True),
        claim("add", "C_DELTA_R_COMPLETE_RENDERING_CONTRAST", "V7 wording could imply a uniquely identified teachability mechanism.", "Delta_R is only the T-versus-D incremental immediate selective-advice-use interaction before personal SLEEP for the complete matched rendering contrast; it remains prospective and unevaluated.", "Powered independent-root D/T correct-versus-none evidence with irrelevant/wrong controls, separate M0 diagnostics, exact target blindness, D/T/M0 competence/nondamage/ceiling/comparable-headroom/equivalence gates, intervals, multiplicity, safety, and claim authority.", False),
        claim("add", "C_DELTA_F_FIXED_TOTAL_REGIME_INTERACTION", "V7 acceleration wording could be read as intrinsic learning rate or parenting-only mediation.", "Delta_F is only the birth-by-fixed-parent total-regime interaction over entry-normalized developmental curves at ages 0,8,16,24,32; it remains prospective and unevaluated.", "Powered primary {D,T} by {absent,fixed} root randomization, fixed-parent exogeneity, matched opportunity, raw curves, common task scale, baseline-adjusted sensitivity, intervals, missingness/capacity, stopping, safety, and G4 authority.", False),
        claim("add", "C_DELTA_E_ADAPTIVE_TOTAL_REGIME_INTERACTION", "V7 could pool adaptive and fixed parenting or imply a parenting-only pathway.", "Delta_E is only the separately randomized birth-by-adaptive-parent total-regime interaction over entry-normalized developmental curves at ages 0,8,16,24,32; it remains prospective and unevaluated.", "Separately powered {D,T} by {absent,adaptive} independent roots under a frozen adaptive context policy, matched opportunity, raw curves, intervals, multiplicity, missingness/capacity, stopping, safety, and G4 authority.", False),
        claim("retire", "C_SLEEP_CADENCE_AS_FORMAL_ESTIMAND", "V7 cadence language could be elevated into an additional formal estimand.", "V8 has exactly three formal estimands: Delta_R, Delta_F, and Delta_E. Replay, rank, cadence, and standardized-terminal comparisons remain controlled secondary obligations and cannot be relabeled as an additional mechanism estimand.", "A separate future deliberation and exact human authority would be required to add another formal estimand.", False),
    ]}


PHASE_REQUIRED_BEFORE = {
    "STATIC_SCHEMA": "implementation",
    "G0_FAKE_RUNTIME": "implementation",
    "G1_IMPLEMENTATION_REVIEW": "model_execution",
    "G2_CPU_DOMAIN": "gpu_run",
    "G3_GPU_SCIENCE": "scientific_claim",
    "G4_CLAIM": "scientific_claim",
}

PHASE_KIND = {
    "STATIC_SCHEMA": "invariant",
    "G0_FAKE_RUNTIME": "unit",
    "G1_IMPLEMENTATION_REVIEW": "independent_review",
    "G2_CPU_DOMAIN": "end_to_end",
    "G3_GPU_SCIENCE": "ablation",
    "G4_CLAIM": "independent_review",
}


def build_acceptance_tests(requirements: dict[str, Any], science: dict[str, Any], systems: dict[str, Any]) -> list[dict[str, str]]:
    obligations = {
        item["family_id"]: item["must_falsify"]
        for item in requirements["acceptance_family_obligations"]
    }
    science_families = {
        item["family_id"]: item for item in science["acceptance_obligation_contract"]["families"]
    }
    system_rows = systems["acceptance_lattice"]["rows"]
    tests: list[dict[str, str]] = []
    for row in system_rows:
        family = science_families[row["family_id"]]
        binding = json.dumps(row, sort_keys=True, separators=(",", ":"))
        consumers = ",".join(row["exact_first_downstream_consumer_action_ids"])
        tests.append({
            "test_id": row["row_id"],
            "kind": PHASE_KIND[row["phase_id"]],
            "setup": (
                f"Prospective UNPRODUCED_UNEVALUATED {row['phase_id']} row for {row['family_id']}. "
                f"Family obligation: {family['requirement']} Exact systems-core row binding: {binding} "
                f"The receipt must bind the future V8 change root, registry root, action-DAG root, all phase-required roots, producer {row['producer_action_id']}, expiry/replay policy, and first consumer(s) {consumers}; no definition is evidence."
            ),
            "expected": (
                f"When separately authorized and constructible, exactly one unique {row['receipt_id']} is produced as PASS or the row is FAIL; "
                "the phase manifest accepts all and only its 21 ordered child roots and every exact first consumer fails closed otherwise."
            ),
            "falsifies": obligations[row["family_id"]],
            "evidence_artifact": (
                "research_loop/changes/chg_20260909_extractable_sleep_bootstrap_v8/evidence/"
                + row["row_id"].lower()
                + ".json"
            ),
            "required_before": PHASE_REQUIRED_BEFORE[row["phase_id"]],
        })
    return tests


def _visibility_elements(systems: dict[str, Any]) -> list[dict[str, Any]]:
    """Materialize object-specific visibility elements from the exact source.

    V7's defect was a principal-by-*capability category* matrix.  V8 instead
    enumerates each actual registry/DAG/test/action/receipt object and every
    concrete producer/consumer bridge presently defined.  A later sealed
    invocation sub-DAG regenerates the same structure for every dynamic action
    instance; no future root count is guessed here.
    """
    registry = systems["canonical_registry_source"]
    dag = systems["finite_action_dag"]
    lattice = systems["acceptance_lattice"]
    actions = {a["action_id"]: a for a in dag["control_actions"]}
    principals = set(registry["registered_principals"])
    sources = {s["source_id"] for s in registry["registered_sources"]}
    stages = principals | sources | {"EXTERNAL_HUMAN_OBSERVER"}
    visibility_sealer = "G0_VISIBILITY_MANIFEST_SEALER"

    elements: dict[str, dict[str, Any]] = {}

    def add(category: str, object_id: str, *, producers: Iterable[str] = (),
            consumers: Iterable[str] = (), observers: Iterable[str] = ()) -> None:
        base_id = f"{category}::{object_id}"
        row = elements.setdefault(base_id, {
            "base_id": base_id,
            "category": category,
            "object_id": object_id,
            "producers": set(),
            "consumers": set(),
            "observers": {visibility_sealer},
        })
        row["producers"].update(producers)
        row["consumers"].update(consumers)
        row["observers"].update(observers)

    # One content root equality-binds all prose/rules that do not carry their
    # own semantic ID; named objects below make the authority-bearing universe
    # independently enumerable.
    add("systems_core", sha256(SYSTEMS_PATH),
        producers=["G0_REGISTRY_GENERATOR"],
        consumers=["G0_ACTION_DAG_GENERATOR", "G0_VISIBILITY_MANIFEST_SEALER"])

    for principal in registry["registered_principals"]:
        add("principal", principal, producers=["G0_REGISTRY_GENERATOR"],
            consumers=[principal])
    for source in sources:
        add("source", source, producers=["G0_REGISTRY_GENERATOR"],
            consumers=[source])
    for lifetime in registry["lifetime_classes"]:
        add("lifetime", lifetime["lifetime_id"],
            producers=["G0_REGISTRY_GENERATOR"])
    for operation in registry["operations"]:
        op = operation["operation"]
        add("operation", op, producers=["G0_REGISTRY_GENERATOR"])
        add("operation_request_schema", operation["request_schema_id"],
            producers=["G0_REGISTRY_GENERATOR"])
        add("operation_result_schema", operation["result_schema_id"],
            producers=["G0_REGISTRY_GENERATOR"])
    for schema in registry["schema_definitions"]:
        add("schema", schema["schema_id"],
            producers=["G0_REGISTRY_GENERATOR"])

    artifact_producer: dict[str, str] = {}
    for artifact in registry["artifact_definitions"]:
        artifact_id = artifact["artifact_class"]
        producer = artifact["sole_producer_id"]
        artifact_producer[artifact_id] = producer
        add("artifact_definition", artifact_id,
            producers=["G0_REGISTRY_GENERATOR"], consumers=[producer])
        add("artifact_payload_schema", artifact["payload_schema_id"],
            producers=["G0_REGISTRY_GENERATOR"], consumers=[producer])
        add("artifact_instance_class", artifact_id, producers=[producer])
    for manifest in registry["materialized_source_product_manifests"]:
        source = manifest["source_id"]
        add("source_product_manifest", source,
            producers=["G0_REGISTRY_GENERATOR"], consumers=[source])
        for artifact_id in manifest["produced_artifact_classes"]:
            add("source_issuance", f"{source}->{artifact_id}",
                producers=[source], consumers=["G0_CAPABILITY_ISSUER"])

    # First pass: exact action objects and their products establish producers.
    receipt_producer: dict[str, str] = {}
    for action in dag["control_actions"]:
        action_id = action["action_id"]
        principal = action["principal_id"]
        add("control_action", action_id,
            producers=["G0_ACTION_DAG_GENERATOR"], consumers=[principal])
        add("terminal_output", action_id, producers=[principal],
            observers=["G0_RESULT_LEDGER"])
        add("error", action_id, producers=[principal],
            observers=["G0_RESULT_LEDGER"])
        for receipt_id in action["produces_receipt_ids"]:
            receipt_producer[receipt_id] = principal
            add("produced_receipt", receipt_id, producers=[principal])
            add("action_result", f"{action_id}->{receipt_id}",
                producers=[principal], observers=["G0_RESULT_LEDGER"])

    # Second pass: every prerequisite becomes one exact capability and bridge
    # template with the action principal as sole consumer.
    for action in dag["control_actions"]:
        action_id = action["action_id"]
        consumer = action["principal_id"]
        for receipt_id in action["prerequisite_receipt_ids"]:
            producer = receipt_producer.get(
                receipt_id, artifact_producer.get(receipt_id,
                "X0_FROZEN_CONTRACT_SOURCE"))
            add("receipt", receipt_id, producers=[producer],
                consumers=[consumer])
            add("capability", f"{receipt_id}->{action_id}",
                producers=["G0_CAPABILITY_ISSUER"], consumers=[consumer])
            add("bridge", f"{receipt_id}->{action_id}",
                producers=["G0_EPOCH_BRIDGE"], consumers=[consumer],
                observers=[producer])

    # Each of the 126 rows and six manifests has a concrete producer and exact
    # first consumers.  This is the static lattice; future result roots remain
    # absent and unevaluated until their authorized phases.
    for row in lattice["rows"]:
        producer_action = actions[row["producer_action_id"]]
        consumers = [actions[a]["principal_id"]
                     for a in row["exact_first_downstream_consumer_action_ids"]]
        add("test_row", row["row_id"],
            producers=[producer_action["principal_id"]], consumers=consumers)
        add("test_receipt", row["receipt_id"],
            producers=[producer_action["principal_id"]], consumers=consumers)
    for manifest in lattice["phase_manifests"]:
        producer_action = actions[manifest["producer_action_ids"][0]]
        consumers = [actions[a]["principal_id"]
                     for a in manifest["first_consumer_action_ids"]]
        add("phase_manifest", manifest["manifest_id"],
            producers=[producer_action["principal_id"]], consumers=consumers)

    for action_kind in dag["protected_action_kinds"]:
        add("protected_action_kind", action_kind,
            producers=["G0_ACTION_DAG_GENERATOR"],
            consumers=["G0_ACTION_INSTANCE_MANIFEST_SEALER"])
    subdag_schema = dag["sealed_subdag_schema"]
    add("sealed_action_instance_schema", subdag_schema["schema_id"],
        producers=["G0_ACTION_DAG_GENERATOR"],
        consumers=["G0_ACTION_INSTANCE_MANIFEST_SEALER"])

    for action_id in systems["g0_echo_closure"]["fixed_authorized_actions"]:
        add("g0_authorization", action_id,
            producers=["X0_EXTERNAL_HUMAN_AUTHORITY_SOURCE"],
            consumers=[actions[action_id]["principal_id"]])
        add("g0_result", action_id,
            producers=[actions[action_id]["principal_id"]],
            consumers=["G0_RESULT_LEDGER", "G0_ACTION_DAG_GATE"])
    add("installed_gate", "G0_INSTALLED_GATE_RECEIPT",
        producers=["G0_ACTION_DAG_GATE"],
        consumers=["G0_ACTION_INSTANCE_MANIFEST_SEALER"])

    # Explicit operation-wire, scientific-evidence, audit, authority, and
    # release objects not already captured by control-action receipts.
    special_sections = {
        "candidate_seal_request": systems["candidate_closure"]["request_schema"]["schema_id"],
        "candidate_seal_result": systems["candidate_closure"]["result_schema"]["schema_id"],
        "cas_request": systems["promotion_cas"]["request_schema"]["schema_id"],
        "cas_result": systems["promotion_cas"]["result_schema"]["schema_id"],
        "cas_idempotency": systems["promotion_cas"]["idempotency_record_schema_id"],
        "release_tuple": systems["release_chain"]["tuple_schema_id"],
    }
    for category, object_id in special_sections.items():
        add(category, object_id, producers=["G0_REGISTRY_GENERATOR"])
    for receipt_id in systems["scientific_edges"]["pre_gpu"]["receipts"]:
        add("typed_scientific_evidence", receipt_id,
            producers=[systems["scientific_edges"]["pre_gpu"]["producer"]],
            consumers=[actions[systems["scientific_edges"]["pre_gpu"]["first_consumer"]]["principal_id"]])
    for receipt_id in systems["scientific_edges"]["claim"]["component_receipts"]:
        add("claim_evidence_component", receipt_id,
            producers=[systems["scientific_edges"]["claim"]["manifest_producer"]],
            consumers=["E9_CLAIM_EVALUATOR"])
    for category, object_id, producer, consumer in (
        ("analysis_packet", "FROZEN_SCIENTIFIC_ANALYSIS_PACKET", "X0_FROZEN_CONTRACT_SOURCE", "E6_SCIENTIFIC_REPORTER"),
        ("audit_finding", "BLINDNESS_AUDIT_FINDING", "E7_BLINDNESS_AUDITOR", "E7_BLINDNESS_AUDITOR"),
        ("audit_finding", "LINEAGE_AUDIT_FINDING", "E7_LINEAGE_SAFETY_AUDITOR", "E7_LINEAGE_SAFETY_AUDITOR"),
        ("audit_attestation", "BLINDNESS_AUDIT_ATTESTATION", "E7_BLINDNESS_AUDITOR", "E8_AUTHORITY_VERIFIER"),
        ("audit_attestation", "LINEAGE_AUDIT_ATTESTATION", "E7_LINEAGE_SAFETY_AUDITOR", "E8_AUTHORITY_VERIFIER"),
        ("authority_verdict", "AUTHORITY_VERDICT", "E8_AUTHORITY_VERIFIER", "E8_RELEASE_CONTROLLER"),
        ("release_wrapper", "RELEASE_TARGET_ARTIFACT", "X0_REGISTERED_RELEASE_ARTIFACT_STORE", "E8_RELEASE_CONTROLLER"),
        ("release_tuple", "RELEASE_TUPLE_EQUALITY_RECEIPT", "E8_AUTHORITY_VERIFIER", "E8_RELEASE_CONTROLLER"),
        ("release_receipt", "RELEASE_RECEIPT", "E8_RELEASE_CONTROLLER", "EXTERNAL_HUMAN_OBSERVER"),
    ):
        add(category, object_id, producers=[producer], consumers=[consumer])

    # Every declared category is represented even when its concrete dynamic
    # instances can exist only after a later sealed per-instance sub-DAG.
    present_categories = {row["category"] for row in elements.values()}
    for category in systems["visibility"]["universe_categories"]:
        if category not in present_categories:
            add("deferred_dynamic_category", category,
                producers=["G0_VISIBILITY_MANIFEST_SEALER"],
                consumers=["G0_ACTION_INSTANCE_MANIFEST_SEALER"])

    for row in elements.values():
        for role in ("producers", "consumers", "observers"):
            unknown = row[role] - stages
            if unknown:
                raise ValueError(
                    f"visibility {row['base_id']} has unknown {role}: {sorted(unknown)}"
                )
        if len(row["producers"]) != 1:
            raise ValueError(
                f"visibility {row['base_id']} must have one producer: "
                f"{sorted(row['producers'])}"
            )
    return [elements[key] for key in sorted(elements)]


def build_visibility(systems: dict[str, Any]) -> dict[str, Any]:
    channels = unique(systems["visibility"]["channels"], "visibility channel")
    registry = systems["canonical_registry_source"]
    stages = list(dict.fromkeys(
        registry["registered_principals"]
        + [s["source_id"] for s in registry["registered_sources"]]
        + ["EXTERNAL_HUMAN_OBSERVER"]
    ))
    elements = _visibility_elements(systems)
    information_items = [
        f"UNIVERSE__{row['base_id']}__{channel}"
        for row in elements for channel in channels
    ]
    cells: list[dict[str, str]] = []
    core_root = sha256(SYSTEMS_PATH)
    for row in elements:
        for channel in channels:
            information_id = f"UNIVERSE__{row['base_id']}__{channel}"
            for stage in stages:
                if stage in row["producers"]:
                    state, role = "visible", "PRODUCER"
                elif stage in row["consumers"]:
                    state, role = "visible", "CONSUMER"
                elif stage in row["observers"]:
                    state, role = "derived_only", "NARROW_OBSERVER"
                else:
                    state, role = "forbidden", "FORBIDDEN"
                cells.append({
                    "information_id": information_id,
                    "stage_id": stage,
                    "visibility": state,
                    "reason": (
                        f"{role} under systems core {core_root} for exact "
                        f"{row['category']} object {row['object_id']}; "
                        f"{channel} is explicitly {state}."
                    ),
                })
    return {"information_items": information_items, "stages": stages,
            "cells": cells}


def build() -> dict[str, Any]:
    loaded = verify_inputs()
    requirements = loaded[str(REQUIREMENTS_PATH.relative_to(ROOT))]
    science = loaded[str(SCIENCE_PATH.relative_to(ROOT))]
    systems = loaded[str(SYSTEMS_PATH.relative_to(ROOT))]
    verify_declared_bindings(requirements, "source_bindings")
    verify_declared_bindings(science, "source_bindings")
    verify_declared_bindings(systems, "bindings")
    if science["self_audit"]["status"] != "pass":
        raise ValueError("scientific core self-audit did not pass")
    assert_equal(systems["integration_contract"]["requirements_id"], requirements["requirements_id"], "systems integration requirements ID")
    expected_rows = verify_phase_lattice(requirements, science, systems)
    verify_registry_and_dag(requirements, systems)

    doc: dict[str, Any] = {
        "schema_version": 1,
        "artifact_type": "architecture_change",
        "change_id": "chg_20260909_extractable_sleep_bootstrap_v8",
        "title": "Extractable SLEEP and target-blind bootstrap v8",
        "summary": (
            "Proposal only: preserve exactly THINK, DREAM, and SLEEP while testing a one-time target-blind T-versus-D birth-rendering contrast that may change later use of waking parenting. Repetition remains waking practice. Personal SLEEP accepts only independently grounded same-life child-authored experience, reconstructs from immutable birth under complete cumulative coverage, closes candidate plus trace atomically before staging, and activates only through one retry-safe full-head compare-and-swap."
        ),
        "system_thesis": (
            "THINK is the continuing waking thought/action/public-outcome stream; DREAM only manages disposable waking context; SLEEP noncreatively compiles independently eligible grounded propositions already authored by the continuing child and writes a fresh-from-birth personal LoRA. The bootstrap, parents, resolvers, stores, evaluators, auditors, gates, registries, receipts, reporters, and release chain are laboratory infrastructure, never additional cognition. Parent or repetition influence reaches SLEEP only through later waking child thought, action, public outcome, complete commit, and independent same-life eligibility."
        ),
        "state": "proposed",
        "context_files": context_files(),
        "graph_delta": build_graph(systems),
        "loop_delta": build_loops(),
        "claim_delta": build_claims(),
        "visibility_matrix": build_visibility(systems),
        "acceptance_tests": build_acceptance_tests(requirements, science, systems),
        "human_boundary": {
            "required": True,
            "decision_owner": "Rohin Ghosh",
            "decision_question": (
                "After at least two fresh-context independent interpretations, an adversarial cross-critique, and adjudicated consensus over these exact V8 bytes dispose every concern, upstream disagreement, visibility failure, missing test, and all 126 rows, does Rohin adopt only this proposal architecture? No intake transition or downstream action is included."
            ),
            "forbidden_before_approval": requirements["authority_boundary"]["forbidden_now"],
        },
    }
    validate_document(doc, requirements, science, systems, expected_rows)
    return doc


def validate_document(
    doc: dict[str, Any], requirements: dict[str, Any], science: dict[str, Any],
    systems: dict[str, Any], expected_rows: list[dict[str, Any]],
) -> None:
    from research_loop.architecture_intake import _validate_schema

    schema = load_json(ROOT / "research_loop/schemas/architecture_change.schema.json")
    errors = _validate_schema(doc, schema, schema)
    if errors:
        raise ValueError("architecture-change schema failure:\n- " + "\n- ".join(errors))

    assert_equal(doc["state"], "proposed", "proposal state")
    assert_equal([entry["path"] for entry in doc["context_files"]], [entry[0] for entry in INPUTS], "context path set/order")
    for entry in doc["context_files"]:
        assert_equal(sha256(ROOT / entry["path"]), entry["sha256"], f"rendered context hash {entry['path']}")

    test_ids = ids(doc["acceptance_tests"], "test_id", "top-level acceptance-test ID")
    assert_equal(test_ids, [row["row_id"] for row in expected_rows], "top-level 126-row ID order")
    assert_equal(len(test_ids), 126, "top-level acceptance-test count")
    phase_for = {row["row_id"]: row["phase_id"] for row in expected_rows}
    for test in doc["acceptance_tests"]:
        phase = phase_for[test["test_id"]]
        assert_equal(test["required_before"], PHASE_REQUIRED_BEFORE[phase], f"required_before {test['test_id']}")
        if "UNPRODUCED_UNEVALUATED" not in test["setup"]:
            raise ValueError(f"row omits prospective state: {test['test_id']}")

    matrix = doc["visibility_matrix"]
    visibility_elements = _visibility_elements(systems)
    expected_items = [
        f"UNIVERSE__{element['base_id']}__{channel}"
        for element in visibility_elements
        for channel in systems["visibility"]["channels"]
    ]
    expected_stages = list(dict.fromkeys(
        systems["canonical_registry_source"]["registered_principals"]
        + [
            source["source_id"]
            for source in systems["canonical_registry_source"]["registered_sources"]
        ]
        + ["EXTERNAL_HUMAN_OBSERVER"]
    ))
    assert_equal(matrix["information_items"], expected_items, "object-specific systems-derived visibility universe")
    assert_equal(matrix["stages"], expected_stages, "object-specific systems-derived visibility stages")
    expected_pairs = {(item, stage) for item in matrix["information_items"] for stage in matrix["stages"]}
    actual_pairs = [(cell["information_id"], cell["stage_id"]) for cell in matrix["cells"]]
    assert_equal(len(actual_pairs), len(expected_pairs), "visibility cell count")
    assert_equal(set(actual_pairs), expected_pairs, "visibility exact cartesian product")
    if len(actual_pairs) != len(set(actual_pairs)):
        raise ValueError("duplicate visibility cells")

    organism = systems["organism_boundary"]
    assert_equal(organism["functions_exactly"], ["THINK", "DREAM", "SLEEP"], "systems organism function set")
    assert_equal(list(science["organism_boundary"]["functions"]), ["THINK", "DREAM", "SLEEP"], "scientific organism function set")
    cognitive_nodes = [node["node_id"] for node in doc["graph_delta"]["nodes"] if node["node_id"] in {"THINK", "DREAM", "SLEEP"}]
    assert_equal(cognitive_nodes, ["THINK", "DREAM", "SLEEP"], "proposal cognitive nodes")
    assert_equal(requirements["cardinality_contract"]["formal_estimand_ids"], ["Delta_R", "Delta_F", "Delta_E"], "formal estimands")
    assert_equal(science["formal_estimands"]["primary_estimand_count"], 3, "scientific estimand count")

    artifact_classes = {item["artifact_class"] for item in systems["canonical_registry_source"]["artifact_definitions"]}
    for item in doc["loop_delta"]["loops"]:
        unknown = set(item["reads"] + item["writes"]) - artifact_classes
        if unknown:
            raise ValueError(f"loop {item['loop_id']} uses unregistered artifact classes: {sorted(unknown)}")

    serialized = json.dumps(doc, sort_keys=True)
    for forbidden in requirements["required_v8_object_identities"]["forbidden_stale_ids"]:
        if forbidden in serialized:
            raise ValueError(f"proposal contains forbidden stale ID: {forbidden}")
    for prohibited in ("192-example", "habit_count", "32 examples per habit", "six-habit"):
        if prohibited.lower() in serialized.lower():
            raise ValueError(f"proposal prematurely fixes bootstrap content: {prohibited}")
    if doc["human_boundary"]["forbidden_before_approval"] != requirements["authority_boundary"]["forbidden_now"]:
        raise ValueError("human boundary does not repeat exact forbidden scope")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true", help="render compact JSON without writing")
    parser.add_argument("--compact", action="store_true", help="write compact JSON")
    args = parser.parse_args()
    doc = build()
    if args.stdout:
        print(json.dumps(doc, sort_keys=False, separators=(",", ":")))
        return
    rendered = json.dumps(doc, separators=(",", ":")) if args.compact else json.dumps(doc, indent=2)
    OUT.write_text(rendered + "\n")
    from research_loop.architecture_intake import validate_change
    validate_change(ROOT, OUT)


if __name__ == "__main__":
    main()
