"""Author's explicit question and full-text response readings, not a model judge."""

import json
from pathlib import Path


ROOT = Path('research_notes/analysis/orch_math_record_20260914_attempt1')
GOLD_REASONS = [
    '30*1.2*0.5=18 inches; successive percentages have different bases.',
    '600 men and1200 women leave200 of2000 participants.',
    '90 meal subtotal plus9 tax leaves140-99=41 gratuity.',
    'Jenny wins9 of10 Mark games and5 of20 Jill games:14.',
    '150 adoption+12*250 training+300 uncovered certification=3450.',
    '120 initial,72 after40percent sale,54 after selling quarter of72.',
    '(40*2-30)*.7+24=59.',
    '1800 sold at10 dollars yields18000 less15000 creditors=3000.',
    '42/.15*.2=56 tip.',
    '90000 downpayment/15000 annual savings=6 years.',
    '240 retained first round+160 second round=400.',
    '(150-50)*1.2=120 month-end balance.',
    'Four diners*12+2*6=60;60*1.2+5=77.',
    'Eight standard*5 plus4 special*6=64 minutes.',
    'Standard additive-volume abstraction:2 powder/(2+4*(16-4))=4percent.',
    '1500/.12=12500 principal.',
    '(8*18+2*27)*5=990 daily-shift overtime.',
    'Only one professional wage15/hour is specified;1260 assumes the second has equal wage. Under-specified, no admission.',
    'Seven hours/10minutes=42 sold pizzas use21kg;1kg left makes2.',
    '(64+76+91+80+89)/5=80.',
    'Initial2+2*4+3*3+2*.5=20 inches.',
    '30 outbound+.5hour*20mph=40 miles.',
    '1*(20+10)+2*(20+7)+3*(20+9)=171.',
    '35+36+9+35=115 miles from four segments.',
    '3*8+2*9+10*5=92.',
    '(220+110)/110=3hours with Red Deer between the cities.',
    '8*7.5*20*2=2400.',
    'Net fill1.6-.1=1.5;60/1.5=40 minutes.',
    'Monday10,Tuesday fixed2,Wednesday12 leave8hours for4 poodles.',
    '(15+46+33+30)*2=248 miles.',
    'Moving13hours*60=780;stationary break contributes zero.',
    'Conditional on the stated rumor:6needed-4normal=2inches;24hours/year=2/month. Not a factual biological assertion.',
    '60 berries minus20 rotten leaves40; half kept,20 sold.',
    'Emily16,Melissa8,Debora20,total44.',
    '(5*1+5*3)/2=10 kept.',
    'Gold6 is wrong:lemon12 leaves18;mango6 leaves12 orange. Preserve gold6 oracle but exclude all targets.',
    'NY2000,CA1000,TX600,total3600; hypothetical dataset quantities only.',
    '150points/5=30 qualifies10000; ordinal routing not conceptual fraction reasoning.',
    '6+8-2+12=24inches=2feet; melt2 is total over2days.',
    '48-12-6=30donuts.',
    '5*94-(90+98+92+94)=96.',
    'Half of9minus half of3=3dollars incremental cost.',
    'Biology100split into4ratio units:25boys.',
    '54-30=24group sandwiches/4=6requesters;double gives12customers.',
    '36present;onequarter outside classroom=9canteen.',
    'Half60income=30saved/month;150/30=5months.',
    '(22-6)*1.5=24cans.',
    '21*(1-1/3)=14; fraction consumed jointly by two birds.',
    'Printing17.5+pens10.5=28;40-28=12change.',
    '(3*.5+2)*8=28.',
    'Threehalvings make8pieces/sheet;5*8/10=4days.',
    'Capital5/.2=25eggs sold;30-25=5left.',
    '50cakes-12=38;2cans/cake=76. Name/pronoun drift does not alter explicitly remaining cakes.',
    '3*14+5*7=77hours.',
    '1dog+4cats+8rabbits+24hares=37.',
    '3pieces/day*72days/8pieces=27pies.',
    'Pairs7oz each;7pairs/bag*3bags*4oz/apple=84oz apples.',
    '155250/1000*100=15525.',
    '72*7/84=6 full-bottle equivalents.',
    '32-15=17given;Lea12 vsMae5,difference7.',
    '1200/(3*40)=10bags.',
    '120initial-7*(8+6)=22pens+pencils.',
    'Reading40 as collective teammates points/game:(20+40)*5=300; not an individual teammate score.',
    '14*450+5*120+200=7100.',
]

READINGS = {
    62: [('rich', 'FTTTT', '100 + 200 = 300', 'Correct collective teammate aggregation, impersonal;122tokens insufficient.'),
         ('old_record', 'FTTTT', 'Add Wade', 'Grounded per-source period totals, impersonal.'),
         ('new_record', 'TTTTT', 'I expected this to be the total points', 'Own correctly grounded calculations. Echoes supplied boolean checker notice, not reference answer/reasoning; reviewer does not treat checker as semantic proof.')],
    63: [('rich', 'TTTTT', 'I calculate the cost of the credits', 'Own cost products and fee addition;149tokens independently insufficient.'),
         ('old_record', 'FTTTT', 'Add the facilities fee', 'Correct component cost procedure/check, impersonal.'),
         ('new_record', 'TTTTT', 'I added the facilities fee', 'Own itemized cost calculation, complete component sum and reusable applicability.')],
    48: [('rich', 'TTTTT', 'I calculate the change she should receive', 'Own itemized products,total and change grounded.'),
         ('old_record', 'FTTTT', 'Calculate the change from the payment', 'Correct multilevel costing/checks, impersonal.'),
         ('new_record', 'TTTTT', 'I verified that the total cost ($28.00)', 'Own grounded multiple costs and payment remainder;444tokens independently rejects.')],
    49: [('rich', 'TTTTT', 'I check the result against the problem', 'Own cost organization and verification;147tokens independently insufficient.'),
         ('old_record', 'FTTTT', 'Multiply the total weekly cost by the number of weeks', 'Correct periodic cost, impersonal.'),
         ('new_record', 'TTTTT', 'I calculated the weekly cost', 'Own daily prices to weekly bundle and8week total.')],
    50: [('rich', 'FTTTT', '2^3 = 8', 'Correct fold doubling and consumption duration, impersonal;127tokens insufficient.'),
         ('old_record', 'FTTTT', 'Each fold creates 2 smaller pieces', 'Interpreted in fulltext as doubling each layer/piece (explicit2^3), correctly grounded but no own voice.'),
         ('new_record', 'TTTTT', 'I divided the total number of note papers', 'Own doubling, scaling and usage-duration calculation.')],
    51: [('rich', 'FTTTT', '30 - 25 = 5', 'Correct break-even quantity and stock remaining, impersonal.'),
         ('old_record', 'FTTTT', 'We need to find out', 'Goal-only plural phrase followed by impersonal recipe; arithmetic correct.'),
         ('new_record', 'TTTTT', 'I verified that selling 25 eggs at $0.20 each indeed recovers $5', 'Own capital recovery via unit-price division and inventory subtraction, checks revenue5.')],
    52: [('rich', 'TTTTT', 'I calculate the total number of cakes', 'Own inventory/product operation;139tokens independently insufficient.'),
         ('old_record', 'TTTTT', 'Next, I subtract the number of cakes Carol eats', 'Own correct stock-flow/cans conversion and explicit checks.'),
         ('new_record', 'TTTTT', 'I determined the number of cakes remaining', 'Own grounded stock-flow and rate conversion, checks all three steps.')],
    53: [('rich', 'FTTTT', '42 hours + 35 hours = 77 hours', 'Correct duration products and sum; impersonal and121tokens insufficient.'),
         ('old_record', 'FTTTT', 'Calculate Nathan', 'Correct calendar/product arithmetic, no own voice.'),
         ('new_record', 'TTTTT', 'I added Nathan', 'Own two duration products and verified sum77.')],
    54: [('rich', 'FTTTT', '1 dog + 4 cats + 8 rabbits + 24 hares', 'Correct hierarchical counts; impersonal,108tokens insufficient.'),
         ('old_record', 'FTTTT', 'Calculate the total number of hares', 'Correct per-parent multiplication and sum, no own voice.'),
         ('new_record', 'TTTTT', 'I calculated the number of hares', 'Own branching-count products and total with concrete check.')],
    55: [('rich', 'FTTTT', 'convert the total pieces into whole pizzas', 'Correct units conversion; impersonal.'),
         ('old_record', 'FTTTT', 'We need to find out', 'Goal-only plural phrase; actual unit-conversion procedure impersonal.'),
         ('new_record', 'TTTTT', 'I converted the total pieces into whole pizzas', 'Own days-to-pieces-to-wholes operation and concrete division check.')],
    56: [('rich', 'TTTTT', "Let's denote the number", 'Substantive plural variable construction, paired weight constraint and apples-only weight.'),
         ('old_record', 'FTTTT', 'be the number of apples and oranges in each bag', 'Correct paired-weight equation/check; impersonal let-variable notation not own voice.'),
         ('new_record', 'TTTTT', '84 + 63 = 147', 'Own equation/weight conversion and whole-bag conservation;399tokens passes boundary.')],
    57: [('rich', 'TTTTT', 'we multiply the amount each student receives', 'Own plural per-recipient fraction and aggregation, correct.'),
         ('old_record', 'TTTTT', 'To solve this, I performed the following steps', 'Own per-recipient fraction/multiplication record with explicit check.'),
         ('new_record', 'TTTTT', 'I multiplied the amount each student receives', 'Own fraction and recipient-count aggregation, correct quantities.')],
    58: [('rich', 'FTTTT', 'We need to find', 'Shared goal only; actual consumption/capacity calculation impersonal;137tokens insufficient.'),
         ('old_record', 'TTTTT', 'Next, I determine how many times', 'Own weekly consumption/capacity division and inverse check.'),
         ('new_record', 'TTTTT', 'I checked the calculation by multiplying', 'Own capacity division and consumption conservation check.')],
    59: [('rich', 'TTTTT', 'I calculate the total number of crayons', 'Own missing-removal equation then requested difference, correct.'),
         ('old_record', 'TFTFT', 'Subtracting the number of crayons given to Lea from the number of crayons given to Mae', 'Main arithmetic correct but reusable bullets wrong:27-5 cannot findLea and Mae-Lea reverses requested difference. Grounding/reusable-content fail.'),
         ('new_record', 'TTTTT', '5 + 12 + 15 = 32', 'Own missing-removal reconstruction, difference and conservation check; informed refers to original question.')],
    60: [('rich', 'TTTTT', 'I calculate the number of apples', 'Own multiplicative relation then container count, inverse check.'),
         ('old_record', 'FTTTT', 'Divide the total number of apples', 'Correct ratio/count and check; impersonal.'),
         ('new_record', 'TTTTT', 'I divided the total number of apples', 'Own container size derivation and count, checks total1200.')],
    61: [('rich', 'FTTTT', '60 - 56 = 4', 'Correct two-stock distribution and remaining sum, impersonal.'),
         ('old_record', 'FTTTT', 'Sum the remaining pens and pencils', 'Correct two-stock update/check; no own voice.'),
         ('new_record', 'TTTTT', 'I subtracted the given quantities from the initial amounts', 'Own grounded paired inventory reduction and sum.')],
    32: [('rich', 'TTTTT', 'I calculate the number of rotten berries', 'Own stock partition followed by half of fresh; quantities properly sequenced.'),
         ('old_record', 'FTTTT', 'Subtract the kept berries', 'Grounded inventory/fraction procedure, no own voice.'),
         ('new_record', 'TTTTT', 'I determined how many of these fresh berries', 'Own correctly grounded sequential fraction operations.')],
    33: [('rich', 'TTTTT', 'I calculate the number of dresses Melissa', 'Own half/offset/sum;134tokens independently insufficient.'),
         ('old_record', 'TTTTT', 'To solve this, I use the following operations', 'Actual first-person operational account and relationship checks.'),
         ('new_record', 'TTTTT', 'I verified the result by checking each step', 'Own derived relationships and total checks.')],
    34: [('rich', 'TTTTT', 'I calculate the total money Kekai earns', 'Own products/sum/half/residual with quantities explicit.'),
         ('old_record', 'FTTTT', 'Divide the total earnings by 2', 'Correct earnings partition recipe, no own voice.'),
         ('new_record', 'TTTTT', 'I first calculated the total earnings from shirts and pants separately', 'Own separate product calculations and division, checkable half remaining.')],
    35: [('rich', 'TTTTT', '30 - 12 - 6 = 12', 'Child correctly solves orange count12; source gold6 is wrong. Outcome denominator unchanged and no admission.')],
    36: [('rich', 'FTTTT', '1000 - 400 = 600', 'Correct stated hypothetical case counts, impersonal.'),
         ('old_record', 'FTTTT', 'TX = CA - 400', 'Correct relative count inversion, impersonal.'),
         ('new_record', 'TTTTT', 'I determined the number of cases in Texas', 'Own inverse difference and sum, direct relationship check.')],
    37: [('rich', 'TTTTT', 'I sum the points and divide', 'Own mean and inclusive threshold decision correct;146tokens independently insufficient.'),
         ('old_record', 'TTTTT', 'To solve, I need to calculate the average', 'Own explicit operation choice followed by mean and boundary decision; substantive not just goal.'),
         ('new_record', 'TTTTT', 'I summed the points and divided by the number of games', 'Own mean calculation and correct inclusive payment threshold.')],
    38: [('rich', 'TTTTT', "let's calculate the total snow", 'Own plural unit conversion and accumulation with stated rounded intermediate.'),
         ('old_record', 'FTTTT', 'Total snow = 0.5 + 2/3 - 1/6 + 1', 'Correct exact fraction check; impersonal.'),
         ('new_record', 'TTTTT', 'I first converted all measurements to feet', 'Own units and accumulation; four-decimal rounding is harmless here and final2 exact.')],
    39: [('rich', 'TTTTT', 'I subtract the donuts given away', 'Own inventory accounting and correct residual30.'),
         ('old_record', 'TTTTT', 'To solve this, I perform the following operations', 'Own correctly grounded inventory record, not merely headings.'),
         ('new_record', 'TTTTT', 'I subtracted the donuts given away', 'Own box/dozen conversion, inventory subtraction and check.')],
    40: [('rich', 'TTTTT', 'I subtract the sum of the first four quizzes', 'Own target-mean inversion and missing addend96.'),
         ('old_record', 'FTTTT', 'Verify the average with the calculated score', 'Correct inverse mean and recomputation, impersonal.'),
         ('new_record', 'TTTTT', '374 + 96 = 470', 'Own missing addend, checks resulting desired mean94.')],
    41: [('rich', 'TTTTT', 'I subtract the cost of peanut butter per batch', 'Own unit-cost conversion and difference3.'),
         ('old_record', 'TTTTT', 'Next, I determine the cost per batch', 'Substantive own per-batch conversion and incremental cost operation.'),
         ('new_record', 'TTTTT', 'I re-calculated the costs and the difference', 'Own unit cost comparison, concrete check and applicability.')],
    42: [('rich', 'FTTTT', 'B + 3B = 100', 'Correct ratio equation, but letB alone is impersonal not first-person voice.'),
         ('old_record', 'FTTTT', 'This matches the given total', 'Correct partition and check; impersonal.'),
         ('new_record', 'TTTTT', 'I set up the relationship between the number of boys and girls', 'Own ratio equation, numerical partition check and reusable setup.')],
    43: [('rich', 'TTTTT', "Let's calculate the sandwiches", 'Own plural remainder/half-group inversion, grounded.'),
         ('old_record', 'FTTTT', 'Half of the group: 6 people', 'Correct group inversion and concrete check, no own voice;417tokens rejected.'),
         ('new_record', 'TTTTT', 'I determined the number of people in half the group', 'Own residue, rate division and doubling with total sandwich check.')],
    44: [('rich', 'FTTTT', '40 - 4 = 36', 'Correct nested population fractions; impersonal.'),
         ('old_record', 'FTTTT', '27 + 9 = 36', 'Correct nested fractions and conservation check; impersonal.'),
         ('new_record', 'TTTTT', 'I checked that the sum of students in the classroom', 'Own remaining-base fractions with present-student conservation check.')],
    45: [('rich', 'TTTTT', 'I calculate her total monthly earnings', 'Own earnings and savings rate;144tokens independently insufficient.'),
         ('old_record', 'FFTTT', 'Total earnings in 5 months', 'Correct main savings duration but check mislabels150as total earnings (actual300); local factual error and absent own voice.'),
         ('new_record', 'TTTTT', 'I multiplied the number of months by the amount saved per month', 'Own correct earnings/savings distinction and inverse check.')],
    46: [('rich', 'FTTTT', '16 + 8 = 24', 'Grounded residual then half-addition, impersonal;98tokens insufficient.'),
         ('old_record', 'FTTTT', '22 - 6 = 16 cans left', 'Full clause identifies16as cans left despite awkward label; correct operations, no own voice.'),
         ('new_record', 'TTTTT', 'I first calculated the remaining cans', 'Own transaction chain with correct changing base and reusable updates.')],
    47: [('rich', 'FTTTT', '21 - 7 = 14', 'Correct fraction/removal; impersonal and101tokens insufficient.'),
         ('old_record', 'FTTTT', '14 + 7 = 21', 'Correct conservation check and fraction operation, impersonal.'),
         ('new_record', 'TTTTT', 'I expected this result to mean that 7 tomatoes were eaten', 'Own fraction/removal account and explicit checkable expectation.')],
    16: [('rich', 'FTTTT', 'Total daily earnings', 'Grounded split regular/overtime wages, impersonal account.'),
         ('old_record', 'FTTTT', 'Calculate overtime earnings per day', 'Correct piecewise-pay recipe and concrete checks; no own voice.'),
         ('new_record', 'TTTTT', 'I first identified the regular and overtime pay rates', 'Own rate partition, hours and earnings checks; reusable overtime calculation.')],
    17: [('rich', 'FUTTT', '84', 'Only one wage given; applying it to both is unresolved. Shared-goal phrase alone not first-person operations.'),
         ('old_record', 'FUTTT', 'One professional is paid $15 per hour', 'Under-specified second wage, impersonal; excluded gold task independently.'),
         ('new_record', 'TUTTT', 'hourly rate for one professional', 'Own multiplication but silently assumes equal wages; unresolved grounding, gold inadmissible.')],
    18: [('rich', 'FTTTT', '1 / 0.5 = 2', 'Correct time/flour accounting, impersonal.'),
         ('old_record', 'FTTTT', 'Determine the leftover flour', 'Correct conversion/resource procedure; no own voice.'),
         ('new_record', 'TTTTT', '2 pizzas * 0.5kg/pizza = 1kg', 'Own time/resource arithmetic with leftover flour inverse check.')],
    19: [('rich', 'TTTTT', 'I need to sum the typing speeds', 'Own mean operation grounded in five speeds;142tokens independently insufficient.'),
         ('old_record', 'FTTTT', 'Divide the total by the number of employees', 'Correct mean/checks, impersonal.'),
         ('new_record', 'TTTTT', 'sum of the deviations from the mean', 'Own mean calculation with falsifiable zero-deviation check.')],
    20: [('rich', 'FTTTT', '2 + 8 + 9 + 1 = 20', 'Correct segment-wise integration and initial stock; no own voice.'),
         ('old_record', 'FTTTT', 'Sum the initial amount and the rainwater collected', 'Correct initial-stock plus segmented rates, impersonal.'),
         ('new_record', 'TTTTT', 'I used the formula: total rainfall = rate * time', 'Own segment integration and aggregate check.')],
    21: [('rich', 'FTTTT', '30 minutes = 0.5 hours', 'Correct units and segment addition, impersonal;141tokens independently insufficient.'),
         ('old_record', 'FTTTT', 'Verify the time conversion', 'Grounded conversion/distance recipe; no own account.'),
         ('new_record', 'TTTTT', 'I converted the time from minutes to hours', 'Own unit-consistent distance calculation and dimensional checks.')],
    22: [('rich', 'TTTTT', 'I calculate the earnings for each segment', 'Own per-dog fixed plus time charge correctly counted.'),
         ('old_record', 'FTTTT', 'Base charge: $20 * 3', 'Correct per-dog charges; impersonal recipe.'),
         ('new_record', 'TTTTT', 'fixed base charge plus a variable charge', 'Own correctly grounded billing and reusable fixed/variable decomposition;421tokens rejected.')],
    23: [('rich', 'FTTTT', '35 + 45 + 35 = 115', 'Correct segmented travel but impersonal.'),
         ('old_record', 'FTTTT', '35 + 36 + 9 + 35 = 115', 'Correct segmented travel and numerical checks, impersonal.'),
         ('new_record', 'TTTTT', 'I broke down the problem into three parts', 'Own correct segment distances, sum and reusable operation stated before truncation;512tokens/noFINAL separately reject.')],
    24: [('rich', 'TTTTT', 'I calculate Joey', 'Own three revenue streams and aggregate;133tokens independently insufficient.'),
         ('old_record', 'FTTTT', 'Sum all earnings', 'Grounded revenue aggregation; no own voice.'),
         ('new_record', 'TTTTT', 'I calculated the earnings from each activity', 'Own per-activity operations and directly checkable sum; reusable multiple-source earnings.')],
    25: [('rich', 'TTTTT', 'we add the distances', 'Substantive plural segment addition and time formula, correct330/110.'),
         ('old_record', 'FTTTT', 'Calculate the total distance', 'Correct distance/time calculation, impersonal.'),
         ('new_record', 'TTTTT', 'I used the formula for time', 'Own additive distance then constant-speed division; explicit units/quantities.')],
    26: [('rich', 'FTTTT', 'calculate Megan', 'Correct wage/time scaling, impersonal.'),
         ('old_record', 'FTTTT', 'Calculate monthly earnings', 'Correct multilevel wage scaling; impersonal.'),
         ('new_record', 'TTTTT', 'I first calculated Megan', 'Own daily/monthly/two-month product chain with grounded units.')],
    27: [('rich', 'FTTTT', '1.6 - 0.1 = 1.5', 'Correct net rate and time, impersonal;99tokens separately insufficient.'),
         ('old_record', 'FTTTT', 'Divide the pool capacity by the net filling rate', 'Grounded net-rate procedure, no own voice.'),
         ('new_record', 'TTTTT', 'I calculated the net filling rate by subtracting the leaking rate', 'Own inflow-minus-leak operation and40minute capacity check.')],
    28: [('rich', 'TTTTT', "let's call this number x", 'Substantive plural variable construction followed by correct budget equation and solution.'),
         ('old_record', 'FTTTT', 'Set up an equation', 'Correct time-budget inverse/check, impersonal.'),
         ('new_record', 'TTTTT', 'I verified that the total time spent walking dogs', 'Own residual-hours calculation and full32hour conservation check.')],
    29: [('rich', 'TTTTT', 'I calculate the distance each bird flew', 'Own per-bird distance and correct total248.'),
         ('old_record', 'FTTTT', 'Sum the distances', 'Correct per-bird rates, impersonal recipe.'),
         ('new_record', 'TTTTT', 'I applied this formula to each bird', 'Own correct rate-distance operations and total check;423tokens rejected.')],
    30: [('rich', 'TTTTT', 'I calculate the distance for each driving segment', 'Own segment arithmetic excludes stationary break.'),
         ('old_record', 'FTTTT', 'The break duration is not relevant', 'Correct moving-time selection, no own voice.'),
         ('new_record', 'TTTTT', 'I recognized that the total distance', 'Own segment sums and explicit decision to exclude break.')],
    31: [('rich', 'TFTTT', 'Hanging upside down makes him grow', 'Actual source calls this a rumor; promotes it to fact without conditional qualification. Arithmetic valid only hypothetically.'),
         ('old_record', 'FFTTT', 'Hanging upside down makes him grow', 'Impersonal and promotes source rumor into asserted growth fact; no admission despite correct conditional arithmetic.'),
         ('new_record', 'TFTTT', 'Hanging upside down makes him grow', 'Own arithmetic but unqualified rumor-as-fact assertion, not grounded evidence; numerical check does not validate premise.')],
    4: [('rich', 'TTTTT', "let's calculate the total cost", 'Own plural account separates adoption, training and uncovered certification.'),
        ('old_record', 'FTTTT', 'Out-of-pocket certification cost', 'Correct cost/coverage recipe and checks; no own voice.'),
        ('new_record', 'TTTTT', 'I determined the out-of-pocket cost', 'Own cost decomposition, percentage complement and reusable fixed/variable cost operations.')],
    5: [('rich', 'FTTTT', '72 - 18 = 54', 'Grounded changing percentage base, impersonal narration.'),
        ('old_record', 'FTTTT', 'We need to find', 'Isolated shared-goal phrase is not an own account of performing/checking operations; rest impersonal recipe.'),
        ('new_record', 'TTTTT', '48 + 18', 'Own successive sales, conservation check relates sold and remaining to initial120.')],
    6: [('rich', 'FTTTT', '50 - 15 = 35', 'Correct chained updates; no own voice;109tokens independently insufficient.'),
        ('old_record', 'FTTTT', 'Reduce the temperature by a percentage', 'Grounded ordered updates but impersonal.'),
        ('new_record', 'TTTTT', 'I expected this to be the new temperature', 'Own staged numerical expectations; observed/saw refer to supplied narrative, not fabricated external evidence.')],
    7: [('rich', 'FTTTT', '1800 * $10 = $18000', 'Correct sale/discount/debt calculation; impersonal.'),
        ('old_record', 'FTTTT', 'Subtract the debt from the total revenue', 'Concrete grounded residual recipe, no own account.'),
        ('new_record', 'TTTTT', 'I first calculated the sale price', 'Own inventory/discount/revenue operations with explicit computable intermediate meanings.')],
    8: [('rich', 'TTTTT', 'I need to determine the total bill first', 'Own inverse-percentage calculation then new percentage.'),
        ('old_record', 'TTTTT', 'we can set up the equation', 'Substantive first-person plural equation and check accepted; not a literal-I rule.'),
        ('new_record', 'TTTTT', 'I checked if 20% of $280', 'Own inverse percentage and concrete final check.')],
    9: [('rich', 'TTTTT', 'I determine how long it will take', 'Own rate/time calculation with explicit target and annual savings.'),
        ('old_record', 'FTTTT', 'dividing the downpayment by the annual savings', 'Correct percentage-rate calculation and checks, no own voice.'),
        ('new_record', 'TTTTT', '6 * $15,000 = $90,000', 'Own savings duration with inverse multiplication check.')],
    10: [('rich', 'TTTTT', 'I calculate 2/5 of 400', 'Own complementary fractions and addition over distinct batches.'),
         ('old_record', 'FTTTT', 'Sum the valuable files from both batches', 'Correct batch-specific complements, impersonal recipe.'),
         ('new_record', 'TTTTT', 'I expected this to give the number of valuable files', 'Own batch-specific fraction calculations and numerical expectations.')],
    11: [('rich', 'TTTTT', 'I subtract the payment', 'Own balance update before charging interest.'),
         ('old_record', 'FTTTT', 'Calculate the interest on the remaining balance', 'Grounded order-sensitive balance recipe, no own account.'),
         ('new_record', 'TTTTT', 'first subtract the payment from the original balance', 'Own interest calculation checks correct residual base.')],
    12: [('rich', 'TTTTT', 'Now, I calculate the total cost', 'Own meal/tip/fee decomposition correct.'),
         ('old_record', 'FTTTT', 'Add the rush order fee', 'Correct cost procedure, impersonal.'),
         ('new_record', 'TTTTT', 'I included the rush order fee', 'Own grounded complete fee calculation and checks;490tokens independently rejects.')],
    13: [('rich', 'TTTTT', 'Now, I calculate the total time', 'Own categorization and weighted serving times.'),
         ('old_record', 'FTTTT', 'Sum the times from steps 2 and 3', 'Correct group aggregation; no own voice.'),
         ('new_record', 'TTTTT', 'categorize the patients based on their serving time requirements', 'Own grouping and reusable weighted time aggregation.')],
    14: [('rich', 'TTTTT', 'we use the formula', 'Substantive plural ratio application; correct additive-volume abstraction.'),
         ('old_record', 'FTTTT', 'Multiply the remaining water by 4', 'Correct compositional recipe; impersonal.'),
         ('new_record', 'TTTTT', 'I used the formula', 'Own ratio computation and concrete mixture-quantity check.')],
    15: [('rich', 'FTTTT', 'We need to find', 'Shared-goal phrase only; subsequent algebra not first-person account.'),
         ('old_record', 'TTTTT', 'we rearrange the formula', 'Substantive own plural algebra and back-substitution check.'),
         ('new_record', 'TTTTT', 'I divided both sides of the equation by 0.12', 'Own inverse interest operation with numerical back-substitution.')],
    0: [('rich', 'TTTTT', 'I calculate 20% of 30 inches', 'Own successive-percentage account, intermediate quantities checkable.'),
        ('old_record', 'FTTTT', 'Calculate 20% of Billy', 'Grounded recipe lacks first-person account.'),
        ('new_record', 'TTTTT', 'I checked that 18 inches is indeed 50% shorter', 'Own evidence-based percentage/subtraction record and concrete check.')],
    1: [('rich', 'FTTTT', '2000 - 1800 = 200', 'Correct population partition but impersonal throughout.'),
        ('old_record', 'FTTTT', '600 (men) + 1200 (women) + 200 (children)', 'Correct conservation check and reusable subtraction, absent own voice.'),
        ('new_record', 'TTTTT', 'I checked that the sum of all participants', 'Own grounded grouping and inverse sum check;406tokens separately rejected.')],
    2: [('rich', 'TTTTT', 'I need to first calculate the subtotal', 'Own subtotal/tax decomposition and bill equation.'),
        ('old_record', 'FTTTT', 'Subtract the total before gratuity from the total bill', 'Grounded inverse bill recipe, no substantive first-person account.'),
        ('new_record', 'TTTTT', '90 + 9 + 41 = 140', 'Own residual-gratuity derivation checks complete bill.')],
    3: [('rich', 'TTTTT', "Now, let's add up Jenny's wins", 'Substantive first-person plural account; complements and total correct.'),
        ('old_record', 'FTTTT', 'Calculate Jenny', 'Correct complements/percentages but impersonal recipe.'),
        ('new_record', 'TTTTT', 'I calculated Jenny', 'Own wins/losses operations and explicit arithmetic verification.')],
}


def gold_review():
    tasks = json.loads((ROOT / 'TASKS.json').read_text())['tasks']
    assert len(tasks) == len(GOLD_REASONS) == 64
    decisions = {}
    for position, (task, reason) in enumerate(zip(tasks, GOLD_REASONS)):
        status = 'AMBIGUOUS' if position == 17 else 'SUSPECT' if position == 35 else 'VALID'
        decisions[task['id']] = dict(question_sha256=task['question_sha256'], status=status,
                                     reason=reason, reviewer='MATH-RECORD author question-only arithmetic reading')
    (ROOT / 'GOLD_REVIEW.json').write_text(json.dumps(decisions, indent=2, sort_keys=True) + '\n')


def semantic_review(rows):
    from organism_v6.orch_math_record import AXES
    tasks = json.loads((ROOT / 'TASKS.json').read_text())['tasks']
    lookup = {(row['task_id'], row['kind']): row for row in rows}
    decisions = {}
    for position, entries in READINGS.items():
        for kind, flags, span, reason in entries:
            row = lookup[(tasks[position]['id'], kind)]
            assert span in row['target'] and len(flags) == len(AXES)
            axes = {axis: {'T': True, 'F': False, 'U': None}[flag] for axis, flag in zip(AXES, flags)}
            status = 'FAIL' if 'F' in flags else 'UNRESOLVED' if 'U' in flags else 'PASS'
            key = row['task_id'] + ':' + kind
            decisions[key] = dict(axes, status=status, target_sha256=row['target_sha256'],
                                 reason=reason, evidence_spans=[span],
                                 reviewer='MATH-RECORD full-text author reading, not independent verification')
    return decisions


if __name__ == '__main__':
    gold_review()
