"""AlchemyWorld — latent compositional environment (SPEC_V2 §2).

Latents (essence, grade, rule table) are per-run randomized, stable for the
lifetime, and NEVER appear in any emitted text — leakage gate G2 is a grep
over emitted text for essence tokens (property in the physics).
"""

from __future__ import annotations

import dataclasses
import itertools
import numpy as np

REACTIVE = tuple(f"E{i}" for i in range(1, 129))  # internal only — never in text
INERT = "E0"
COLORS = ("amber", "violet", "ashen", "cerulean", "russet", "pale")
SMELLS = ("acrid", "sweet", "loamy", "metallic", "briny", "musky")

_SYL_A = ("vex", "mor", "tes", "gal", "rin", "dru", "kel", "sab",
          "fen", "lur", "os", "quin", "bel", "har", "nym", "cor")
_SYL_B = ("il", "run", "sic", "eth", "ock", "ane", "ura", "esk",
          "ov", "ith", "ard", "une", "yl", "ost", "ira", "em")


_SYL_M = ("", "", "ta", "ne", "go", "shi", "va", "pol")


def _nonce(rng: np.random.Generator, used: set) -> str:
    # 2048 syllabic names; numeric-suffix fallback makes it exhaustion-proof
    for _ in range(40):
        n = rng.choice(_SYL_A) + rng.choice(_SYL_M) + rng.choice(_SYL_B)
        if n not in used:
            used.add(n)
            return n
    n = rng.choice(_SYL_A) + rng.choice(_SYL_B) + str(len(used))
    used.add(n)
    return n


@dataclasses.dataclass
class Ingredient:
    name: str
    essence: str      # hidden
    grade: int        # hidden
    color: str        # visible, independent of essence (false correlate)
    smell: str        # visible, independent of essence


class AlchemyWorld:
    """One life's physics. predict() is ground truth for held-out eval."""

    def __init__(self, n_ingredients: int = 24, n_inert: int = 4,
                 seed: int = 0, n_essences: int = 4, max_tier: int = 3,
                 rho_fn: float = 0.0):
        """rho_fn = fraction of essence-pair rules generated by a hidden
        FUNCTION over class geometry (cycle distance) instead of i.i.d.
        Stratum G: a learner that infers the geometry can predict rules
        never observed in any form. rho_fn=0 reproduces the pure-iid world."""
        rng = np.random.default_rng(seed)
        self.seed = seed
        self.max_tier = max_tier
        self.rho_fn = rho_fn
        self.reactive = REACTIVE[:n_essences]
        # hidden geometry: each essence gets a position on a cycle
        pos = rng.permutation(n_essences)
        self._pos = {e: int(pos[i]) for i, e in enumerate(self.reactive)}
        self._K = n_essences
        used: set = set()
        self.ingredients: dict[str, Ingredient] = {}
        essences = ([INERT] * n_inert +
                    [self.reactive[i % len(self.reactive)]
                     for i in range(n_ingredients - n_inert)])
        rng.shuffle(essences)
        for e in essences:
            name = _nonce(rng, used)
            self.ingredients[name] = Ingredient(
                name, e, int(rng.integers(1, 3)),
                str(rng.choice(COLORS)), str(rng.choice(SMELLS)))
        # rule table over unordered reactive essence pairs.
        # TIERED products (chains): combining tier-n items yields a
        # DISTINCT tier-(n+1) family — deep items require their
        # intermediates, so recipes are real chains, not aliases.
        self.rules: dict[frozenset, tuple] = {}       # pair -> (kind, ...)
        self.products: dict[tuple, str] = {}    # (pairkey, grade, tier)->name
        self.product_essence: dict[str, str] = {}
        self.item_tier: dict[str, int] = {}
        self.pair_stratum: dict[frozenset, str] = {}   # 'iid' | 'fn'
        # shared per-(distance,tier) families for the fn stratum: pairs at
        # the same geometric distance yield the same family — the learnable
        # regularity that predicts NEVER-OBSERVED rules
        fn_fams = {}

        def _fn_products(key, dist):
            for tier in range(1, max_tier + 1):
                if (dist, tier) not in fn_fams:
                    fn_fams[(dist, tier)] = _nonce(rng, used)
                fam = fn_fams[(dist, tier)]
                for g in (1, 2):
                    pname = f"{fam}-{'I' * g}"
                    self.products[(key, g, tier)] = pname
                    if pname not in self.product_essence:
                        self.product_essence[pname] = str(rng.choice(self.reactive))
                        self.item_tier[pname] = tier

        for pair in itertools.combinations_with_replacement(self.reactive, 2):
            key = frozenset(pair) if pair[0] != pair[1] else frozenset([pair[0]])
            if rng.random() < rho_fn:
                self.pair_stratum[key] = "fn"
                d = abs(self._pos[pair[0]] - self._pos[pair[1]])
                d = min(d, self._K - d)
                if d <= self._K // 4:
                    self.rules[key] = ("product",)
                    _fn_products(key, d)
                elif d <= (3 * self._K) // 8:
                    self.rules[key] = ("nothing",)
                else:
                    self.rules[key] = ("ruin",)
                continue
            self.pair_stratum[key] = "iid"
            r = rng.random()
            if r < 0.6:
                self.rules[key] = ("product",)
                for tier in range(1, max_tier + 1):
                    fam = _nonce(rng, used)
                    for g in (1, 2):
                        pname = f"{fam}-{'I' * g}"
                        self.products[(key, g, tier)] = pname
                        self.product_essence[pname] = str(rng.choice(self.reactive))
                        self.item_tier[pname] = tier
            elif r < 0.85:
                self.rules[key] = ("nothing",)
            else:
                self.rules[key] = ("ruin",)

    # ---- ground truth ----------------------------------------------------
    def essence_of(self, item: str) -> str:
        if item in self.ingredients:
            return self.ingredients[item].essence
        return self.product_essence.get(item, INERT)

    def grade_of(self, item: str) -> int:
        if item in self.ingredients:
            return self.ingredients[item].grade
        return 2 if item.endswith("-II") else 1


    def tier_of(self, item: str) -> int:
        return self.item_tier.get(item, 0)

    def predict(self, a: str, b: str) -> tuple:
        """(kind, product_name_or_None) — the held-out eval target."""
        ea, eb = self.essence_of(a), self.essence_of(b)
        if INERT in (ea, eb):
            return ("nothing", None)
        tier = max(self.tier_of(a), self.tier_of(b)) + 1
        if tier > self.max_tier:
            return ("nothing", None)   # over-refined: fizzles
        key = frozenset([ea, eb]) if ea != eb else frozenset([ea])
        rule = self.rules[key]
        if rule[0] != "product":
            return (rule[0], None)
        g = max(self.grade_of(a), self.grade_of(b))
        return ("product", self.products[(key, g, tier)])

    def combine_text(self, a: str, b: str) -> tuple:
        """(kind, product, observation string) — what the agent sees."""
        kind, prod = self.predict(a, b)
        if kind == "product":
            obs = f"You combine {a} and {b}. They fuse into {prod}."
        elif kind == "ruin":
            obs = f"You combine {a} and {b}. The mixture curdles and is ruined."
        else:
            obs = f"You combine {a} and {b}. Nothing happens."
        return kind, prod, obs

    # ---- pools ------------------------------------------------------------
    def base_pairs(self) -> list:
        return list(itertools.combinations(sorted(self.ingredients), 2))

    def craftable_targets(self) -> list:
        """depth-1 product targets with at least one base recipe."""
        out = set()
        for a, b in self.base_pairs():
            kind, prod = self.predict(a, b)
            if kind == "product":
                out.add(prod)
        return sorted(out)

    def build_chain_index(self, max_depth: int = 4):
        """item -> (depth, plan) where plan = list of (a, b, product)
        combines from base ingredients. Depth 0 = base ingredient.
        BFS over the crafting graph; memoized on self."""
        if getattr(self, "_chain_idx", None) is not None:
            return self._chain_idx
        depth = {n: 0 for n in self.ingredients}
        plan = {n: [] for n in self.ingredients}
        frontier = sorted(self.ingredients)
        idx = {}
        for d in range(1, max_depth + 1):
            new = []
            items = sorted(depth)
            for i, a in enumerate(items):
                for b in items[i:]:
                    if max(depth[a], depth[b]) != d - 1:
                        continue  # at least one input from last layer
                    kind, prod = self.predict(a, b)
                    if kind != "product" or prod in depth:
                        continue
                    depth[prod] = d
                    plan[prod] = plan[a] + plan[b] + [(a, b, prod)]
                    new.append(prod)
            if not new:
                break
        self._chain_idx = {p: (depth[p], plan[p]) for p in depth
                           if depth[p] >= 1}
        return self._chain_idx

    def recipe_pairs_for(self, target: str) -> list:
        return [(a, b) for a, b in self.base_pairs()
                if self.predict(a, b) == ("product", target)]

    def sample_holdout(self, frac: float = 0.3, seed: int = 0) -> set:
        """Held-out-by-construction: these pairs are never co-present in any
        episode inventory (env enforces), so the split is physics, not luck."""
        rng = np.random.default_rng(seed + 101)
        pairs = self.base_pairs()
        idx = rng.permutation(len(pairs))[:int(frac * len(pairs))]
        return {tuple(sorted(pairs[i])) for i in idx}

    def stratum_of(self, a: str, b: str) -> str:
        """'iid' | 'fn' | 'inert' — for per-stratum eval reporting."""
        ea, eb = self.essence_of(a), self.essence_of(b)
        if INERT in (ea, eb):
            return "inert"
        key = frozenset([ea, eb]) if ea != eb else frozenset([ea])
        return self.pair_stratum.get(key, "iid")

    def leakage_scan(self, text: str) -> list:
        """G2: any internal essence token in emitted text = leak."""
        toks = set(REACTIVE) | {INERT}
        return [t for t in toks if t in text]
